card(afk).
card(hero_skins).
card(alleria_windrunner).
card(khadgar).
card(lady_liadrin).
card(magni_bronzebeard).
card(medivh).
card(morgl_the_oracle).
card(tyrande_whisperwind).
card(armor_up).
card(ballista_shot).
card(fireblast).
card(fireblast_rank_2).
card(heal).
card(lesser_heal).
card(reinforce).
card(steady_shot).
card(tank_up).
card(the_silver_hand).
card(totemic_call).
card(totemic_slam).
card(credits).
card(andy_brock).
card(bryan_chang).
card(derek_sakamoto).
card(steven_gabriel).
card(becca_abel).
card(jerry_mascho).
card(keith_landes).
card(michael_schweitzer).
card(rachelle_davis).
card(ryan_chew).
card(zwick).
card(ben_brode).
card(bob_fitch).
card(brian_birmingham).
card(cameron_chrisman).
card(eric_del_priore).
card(henry_ho).
card(kyle_harrison).
card(max_ma).
card(beomki_hong).
card(christopher_yim).
card(elizabeth_cho).
card(he-rim_woo).
card(jay_baxter).
card(jeremy_cranford).
card(max_mccall).
card(ricardo_robaina).
card(robin_fredericksen).
card(ryan_masterson).
card(tim_erskine).
card(walter_kong).
card(jason_macallister).
card(jon_bankard).
card(seyil_yoon).
card(yong_woo).
card(ben_thompson).
card(eric_dodds).
card(jason_chayes).
card(jomaro_kindred).
card(jonas_laster).
card(mike_donais).
card(dean_ayala).
card(hamilton_chu).
card(jc_park).
card(rob_pardo).
card(brian_schwab).
card(missions).
card(bananas).
card(hemet_nesingwary).
card(hogger).
card(illidan_stormrage).
card(jaina_proudmoore).
card(king_mukla).
card(legacy_of_the_emperor).
card(lorewalker_cho).
card(might_of_mukla).
card(millhouse_manastorm).
card(transcendence).
card(barrel).
card(barrel_toss).
card(crazed_hunter).
card(crazy_monkey).
card(flame_of_azzinoth).
card(gnoll).
card(naga_myrmidon).
card(pandaren_scout).
card(riverpaw_gnoll).
card(flames_of_azzinoth).
card(hidden_gnome).
card(shado-pan_monk).
card(shotgun_blast).
card(stomp).
card(warglaive_of_azzinoth).
card(flame_burst).
card(hogger_smash).
card(will_of_mukla).
card(brewmaster).
card(massive_gnoll).
card(dual_warglaives).
card(muklas_big_brother).
card(classic).
card(inspired).
card(alexstraszas_fire).
card(ancestral_spirit).
card(ancient_secrets).
card(ancient_teachings).
card(bear_form).
card(berserk).
card(bestial_wrath).
card(bite).
card(blarghghl).
card(blessed_champion).
card(blessing_of_wisdom).
card(blood_pact).
card(bloodrage).
card(bolstered).
card(cannibalize).
card(cat_form).
card(cold_blood).
card(commanding_shout).
card(concealed).
card(consume).
card(demigods_favor).
card(disguised).
card(dispel).
card(elunes_grace).
card(empowered).
card(enraged).
card(equality).
card(equipped).
card(experiments).
card(far_sight).
card(full_belly).
card(full_strength).
card(gladiators_longbow_enchantment).
card(greenskins_command).
card(growth).
card(hand_of_argus).
card(hour_of_twilight).
card(ice_block).
card(infusion).
card(inner_fire).
card(inner_rage).
card(justice_served).
card(keeping_secrets).
card(kill_millhouse).
card(leader_of_the_pack).
card(level_up).
card(mana_gorged).
card(mark_of_nature).
card(mind_controlling).
card(moonfire).
card(mrgglaargl).
card(mrghlglhal).
card(needs_sharpening).
card(nightmare).
card(nourish).
card(overloading).
card(power_of_the_kirin_tor).
card(power_overwhelming).
card(preparation).
card(rampage).
card(raw_power).
card(repentance).
card(rooted).
card(shadow_madness).
card(shadows_of_muru).
card(shandos_lesson).
card(sharp).
card(soul_of_the_forest).
card(stand_down).
card(starfall).
card(strength_of_the_pack).
card(summon_a_panther).
card(teachings_of_the_kirin_tor).
card(tempered).
card(trapped).
card(treasure_crazed).
card(upgraded).
card(uproot).
card(uprooted).
card(vancleefs_vengeance).
card(warded).
card(well_fed).
card(whipped_into_shape).
card(wrath).
card(yarrr).
card(circle_of_healing).
card(demonfire).
card(dream).
card(lord_jaraxxus).
card(shadow_of_nothing).
card(shadowstep).
card(silence).
card(wisp).
card(abusive_sergeant).
card(angry_chicken).
card(argent_squire).
card(battle_axe).
card(blood_imp).
card(bloodsail_corsair).
card(conceal).
card(damaged_golem).
card(defender).
card(defias_bandit).
card(dust_devil).
card(earth_shock).
card(eye_for_an_eye).
card(flame_imp).
card(forked_lightning).
card(heavy_axe).
card(hound).
card(hungry_crab).
card(ice_lance).
card(imp).
card(leper_gnome).
card(lightning_bolt).
card(lightwarden).
card(mana_wyrm).
card(murloc_tidecaller).
card(naturalize).
card(noble_sacrifice).
card(redemption).
card(savagery).
card(secretkeeper).
card(shield_slam).
card(shieldbearer).
card(snake).
card(southsea_deckhand).
card(spellbender).
card(squire).
card(squirrel).
card(upgrade).
card(violet_apprentice).
card(whelp).
card(worgen_infiltrator).
card(worthless_imp).
card(young_dragonhawk).
card(young_priestess).
card(amani_berserker).
card(ancient_watcher).
card(argent_protector).
card(armorsmith).
card(battle_rage).
card(betrayal).
card(bloodmage_thalnos).
card(bloodsail_raider).
card(crazed_alchemist).
card(cruel_taskmaster).
card(defias_ringleader).
card(dire_wolf_alpha).
card(doomsayer).
card(eviscerate).
card(explosive_trap).
card(faerie_dragon).
card(flare).
card(freezing_trap).
card(hyena).
card(inferno).
card(knife_juggler).
card(lightwell).
card(loot_hoarder).
card(mad_bomber).
card(mana_addict).
card(mana_wraith).
card(master_swordsmith).
card(mind_shatter).
card(mind_spike).
card(misdirection).
card(nat_pagle).
card(panther).
card(patient_assassin).
card(pint-sized_summoner).
card(power_of_the_wild).
card(scavenging_hyena).
card(slam).
card(snake_trap).
card(snipe).
card(sorcerers_apprentice).
card(spirit_wolf).
card(stormforged_axe).
card(sunfury_protector).
card(treant).
card(wild_pyromancer).
card(youthful_brewmaster).
card(ysera_awakens).
card(acolyte_of_pain).
card(alarm-o-bot).
card(aldor_peacekeeper).
card(arcane_golem).
card(blood_fury).
card(blood_knight).
card(coldlight_oracle).
card(coldlight_seer).
card(counterspell).
card(deadly_shot).
card(demolisher).
card(divine_favor).
card(eaglehorn_bow).
card(earthen_ring_farseer).
card(edwin_vancleef).
card(emperor_cobra).
card(felguard).
card(feral_spirit).
card(finkle_einhorn).
card(flesheating_ghoul).
card(frothing_berserker).
card(harvest_golem).
card(headcrack).
card(ice_barrier).
card(imp_master).
card(injured_blademaster).
card(ironbeak_owl).
card(jungle_panther).
card(kirin_tor_mage).
card(laughing_sister).
card(lava_burst).
card(lightning_storm).
card(mana_tide_totem).
card(mind_control_tech).
card(mirror_entity).
card(murloc_warleader).
card(perditions_blade).
card(questing_adventurer).
card(raging_worgen).
card(scarlet_crusader).
card(sense_demons).
card(shadowform).
card(si:seven_agent).
card(southsea_captain).
card(sword_of_justice).
card(tauren_warrior).
card(thoughtsteal).
card(thrallmar_farseer).
card(tinkmaster_overspark).
card(unbound_elemental).
card(unleash_the_hounds).
card(vaporize).
card(void_terror).
card(ancient_brewmaster).
card(ancient_mage).
card(arathi_weaponsmith).
card(auchenai_soulpriest).
card(baine_bloodhoof).
card(blade_flurry).
card(cone_of_cold).
card(cult_master).
card(dark_iron_dwarf).
card(defender_of_argus).
card(dread_corsair).
card(emerald_drake).
card(ethereal_arcanist).
card(keeper_of_the_grove).
card(lightspawn).
card(mass_dispel).
card(master_of_disguise).
card(mindgames).
card(mogushan_warden).
card(mortal_strike).
card(pit_lord).
card(shadowflame).
card(silvermoon_guardian).
card(spellbreaker).
card(summoning_portal).
card(twilight_drake).
card(violet_teacher).
card(abomination).
card(ashbringer).
card(azure_drake).
card(bane_of_doom).
card(big_game_hunter).
card(brawl).
card(captain_greenskin).
card(devilsaur).
card(doomguard).
card(doomhammer).
card(druid_of_the_claw).
card(earth_elemental).
card(explosive_shot).
card(faceless_manipulator).
card(fen_creeper).
card(force_of_nature).
card(harrison_jones).
card(holy_wrath).
card(leeroy_jenkins).
card(silver_hand_knight).
card(spiteful_smith).
card(stampeding_kodo).
card(stranglethorn_tiger).
card(venture_co_mercenary).
card(argent_commander).
card(avenging_wrath).
card(blizzard).
card(cabal_shadow_priest).
card(cairne_bloodhoof).
card(frost_elemental).
card(gadgetzan_auctioneer).
card(holy_fire).
card(infernal).
card(kidnapper).
card(priestess_of_elune).
card(savannah_highmane).
card(siphon_soul).
card(sunwalker).
card(sylvanas_windrunner).
card(temple_enforcer).
card(the_beast).
card(the_black_knight).
card(windfury_harpy).
card(ancient_of_lore).
card(ancient_of_war).
card(archmage_antonidas).
card(baron_geddon).
card(gladiators_longbow).
card(gorehowl).
card(prophet_velen).
card(ravenholdt_assassin).
card(alakir_the_windlord).
card(grommash_hellscream).
card(gruul).
card(lay_on_hands).
card(ragnaros_the_firelord).
card(tirion_fordring).
card(twisting_nether).
card(alexstrasza).
card(cenarius).
card(king_krush).
card(malygos).
card(nozdormu).
card(onyxia).
card(ysera).
card(deathwing).
card(pyroblast).
card(sea_giant).
card(mountain_giant).
card(molten_giant).
card(promo).
card(emboldened).
card(transformed).
card(chicken).
card(murloc).
card(emboldener_3000).
card(homing_chicken).
card(poultryizer).
card(repair_bot).
card(i_am_murloc).
card(power_of_the_horde).
card(rogues_do_it).
card(elite_tauren_chieftain).
card(gelbin_mekkatorque).
card(karazhan).
card(a_simple_trick).
card(arcanely_powerful).
card(big_bad_wolf).
card(black_king).
card(blue_beam).
card(coalesce_the_moonlight).
card(curator).
card(dark_pact).
card(death-marked_love).
card(drink_the_moonlight).
card(eating).
card(enfeeble).
card(filled_up).
card(gallery_protection).
card(incredible_impression).
card(insightful).
card(julianne).
card(kindly_grandmother).
card(magic_mirror).
card(manastorm).
card(nazra_wildaxe).
card(nether_breath).
card(nether_rage).
card(netherspite).
card(nightbane).
card(prince_malchezaar).
card(protecting_the_gallery).
card(red_beam).
card(reflection).
card(reflections).
card(secrets_of_karazhan).
card(shade_of_aran).
card(silver_might).
card(silverware_golem).
card(table_set).
card(terestian_illhoof).
card(the_crone).
card(trembling_before_the_wolf).
card(white_king).
card(be_our_guest).
card(evocation).
card(ley_lines).
card(trembling).
card(true_love).
card(twister).
card(arcane_anomaly).
card(astral_portal).
card(babbling_book).
card(black_pawn).
card(blue_portal).
card(candle).
card(castle).
card(enchanted_raven).
card(icky_imp).
card(mage_armor).
card(malchezaars_imp).
card(murloc_escaping).
card(murlocs_escaping).
card(pawn).
card(plate).
card(runic_egg).
card(spirit_claws).
card(spoon).
card(steward).
card(swashburglar).
card(white_pawn).
card(animated_shield).
card(arcane_power).
card(archmages_apprentice).
card(big_bad_claws).
card(brilliance).
card(broom).
card(cat_trick).
card(cheat).
card(cup).
card(empowerment).
card(fork).
card(legion).
card(maelstrom_portal).
card(many_imps).
card(mediva_1).
card(mediva_2).
card(mediva_3).
card(medivhs_valet).
card(netherspite_historian).
card(orc_warrior).
card(pompous_thespian).
card(purify).
card(stampeding_beast).
card(terrifying_roar).
card(the_horde).
card(archmages_insight).
card(atiesh).
card(black_bishop).
card(black_rook).
card(cat_in_a_hat).
card(cellar_spider).
card(cloaked_huntress).
card(deadly_fork).
card(demonic_presence).
card(demons_loose).
card(flame_wreath).
card(flying_monkey).
card(haywire_mech).
card(knife).
card(mime).
card(moroes).
card(mysterious_rune).
card(nightbane_templar).
card(pantry_spider).
card(party_elemental).
card(pour_a_round).
card(protect_the_king).
card(romulo).
card(shadow_bolt_volley).
card(sharp_fork).
card(teapot).
card(violet_illusionist).
card(white_bishop).
card(white_rook).
card(zoobot).
card(arcanosmith).
card(barnes).
card(black_knight).
card(dorothee).
card(kilrek).
card(pitcher).
card(priest_of_the_feast).
card(set_the_table).
card(shadow_volley).
card(silvermoon_portal).
card(steal_life).
card(summon_kilrek).
card(white_knight).
card(wicked_witchdoctor).
card(avian_watcher).
card(dragons_free).
card(ethereal_peddler).
card(fools_bane).
card(ironforge_portal).
card(kara_kazham).
card(menagerie_magician).
card(onyx_bishop).
card(red_riding_hood).
card(tossing_plates).
card(abyssal).
card(book_wyrm).
card(ivory_knight).
card(menagerie_warden).
card(moat_lurker).
card(moonglade_portal).
card(black_queen).
card(firelands_portal).
card(the_curator).
card(white_queen).
card(medivh_the_guardian).
card(red_portal).
card(arcane_giant).
card(tavern_brawl).
card(annoy-o-tron).
card(annoy-o-tron_prime).
card(battlecry_bonus).
card(big_banana).
card(blingtrons_blade).
card(blingtrons_blade_hero).
card(bomb_salvo).
card(bonus).
card(boom_bot).
card(boss_hp_swapper).
card(burning_adrenaline).
card(charge).
card(cheap_gift).
card(choose_one_of_three).
card(city_of_stormwind).
card(cowed).
card(create_15_secrets).
card(dark_power).
card(deathrattle_bonus).
card(deckbuilding_enchant).
card(deviate_switch).
card(dire_fate_card).
card(dire_fate_manaburst).
card(dire_fate_murlocs).
card(dire_fate_taunt_and_charge).
card(dire_fate_unstable_portals).
card(dire_fate_windfury).
card(double_zap).
card(dragonlust).
card(draw_offensive_play).
card(endless_enchantment).
card(enough).
card(facilitated).
card(fate).
card(fate_11_ench_murloc).
card(fate_12_ench_confuse).
card(fate_7_ench_2nd).
card(fate_7_ench_get_a_coin).
card(fate_8_get_armor).
card(fate_8_rand_2_armor_each_turn).
card(fate_9_ench_deathrattle_bonus).
card(fate_armor).
card(fate_bananas).
card(fate_coin).
card(fate_confusion).
card(fate_portals).
card(fate_spells).
card(getting_angry).
card(give_taunt_and_charge).
card(going_nova).
card(hardpacked_snowballs).
card(i_hear_you).
card(kelthuzad).
card(kill_the_lorewalker).
card(living_bomb).
card(miniature).
card(murloc_bonus).
card(my_deck_id).
card(mystery_pilot).
card(nefarian).
card(overclock).
card(pick_your_fate_1_ench).
card(pick_your_fate_2_ench).
card(pick_your_fate_3_ench).
card(pick_your_fate_4_ench).
card(pick_your_fate_5_ench).
card(pick_your_fate_build_around).
card(pick_your_fate_random).
card(pick_your_fate_randon_2nd).
card(pick_your_second_class).
card(player_choice_enchant).
card(player_choice_enchant_on_curve).
card(player_choice_enchant_on_curve2).
card(prioritize).
card(rafaam).
card(release_coolant).
card(repurposed).
card(saddened).
card(saddened_hero_enchant).
card(safe).
card(second_class_druid).
card(second_class_hunter).
card(second_class_mage).
card(second_class_paladin).
card(second_class_priest).
card(second_class_rogue).
card(second_class_shaman).
card(second_class_warlock).
card(second_class_warrior).
card(shadow_tower_give_my_minions_stealth).
card(shadow_tower_stealth).
card(sharpened).
card(spell_bonus).
card(strength_of_stormwind).
card(tb_clockworkcarddealer).
card(tb_decreasingcardcost).
card(tb_enchwhosthebossnow).
card(tbdecreasingcardcostdebug).
card(tbfactionwarboombot).
card(tbmechwarcommoncards).
card(tbrandomcardcost).
card(tbud_summon_early_minion).
card(team_player_enchantment).
card(transmute_your_minions).
card(unity).
card(valeera_sanguinar).
card(why_wont_you_die).
card(will_of_stormwind).
card(yogg_servant_hero_enchant).
card(alms_of_light).
card(bamboozle).
card(choose_a_new_card).
card(cleave).
card(dont_push_me).
card(elemental_eruption).
card(explosive_rune).
card(explosive_runes).
card(flame_missiles).
card(glorious_finale).
card(immolate).
card(jeering_crowd).
card(me_smash).
card(offensive_play).
card(oldtbst_push_common_card).
card(quest_coin).
card(secrets_of_shadow).
card(tarnished_coin).
card(tb_enchrandommanacost).
card(twisted_light).
card(winters_veil_gift).
card(armory).
card(decimate).
card(deviate_banana).
card(fallout_slime).
card(foam_sword).
card(herold).
card(oldn3wb_healer).
card(oldn3wb_mage).
card(oldn3wb_tank).
card(rotten_banana).
card(stolen_winters_veil_gift).
card(tbfactionwarboombotspell).
card(activate).
card(barracks).
card(battle_standard).
card(bone_minions).
card(boom_bot_jr).
card(call_mediva).
card(cash_in).
card(die_insect).
card(harvest).
card(hello_hello_hello).
card(living_lava).
card(mech_fan).
card(molten_rage).
card(necromancy).
card(open_the_gates).
card(pile_on).
card(pirate).
card(poison_cloud).
card(rock_elemental).
card(shadow_or_light).
card(sharpen).
card(shieldsman).
card(staff_of_origination).
card(staff_first_piece).
card(staff_two_pieces).
card(sulfuras).
card(swat_fly).
card(the_majordomo).
card(uncover_staff_piece).
card(web_wrap).
card(whirling_ash).
card(wild_magic).
card(core_hound_pup).
card(core_hound_puppies).
card(dragonscale_warrior).
card(heigan_the_unclean).
card(high_justice_grimstone).
card(massive_runeblade).
card(moira_bronzebeard).
card(oldlegit_healer).
card(oldpvp_rogue).
card(omnotron_defense_system).
card(party_portal).
card(son_of_the_flame).
card(spectral_gothik).
card(swordsman).
card(annoy-o-tron_fanclub).
card(anubrekhan).
card(atramedes).
card(coren_direbrew).
card(gluth).
card(gothik_the_harvester).
card(grand_widow_faerlina).
card(lady_blaumeux).
card(lucifron).
card(main_tank).
card(raid_healer).
card(sir_zeliek).
card(dragonkin_spellcaster).
card(freewheeling_skulker).
card(garr).
card(grobbulus).
card(intrepid_dragonstalker).
card(sapphiron).
card(drakonid_slayer).
card(razorgore).
card(vaelastrasz).
card(darkness_calls).
card(instructor_razuvious).
card(patchwerk).
card(noth_the_plaguebringer).
card(gearmaster_mechazod).
card(overloaded_mechazod).
card(golemagg).
card(the_league_of_explorers).
card(animated).
card(archaedas).
card(blessed).
card(blessing_of_the_sun).
card(blessings_of_the_sun).
card(cauldron).
card(chieftain_scarvash).
card(cursed_blade).
card(explorers_hat).
card(famished).
card(fossilized).
card(giantfin).
card(heroic_mode).
card(hollow).
card(investigate_the_runes).
card(lady_nazjar).
card(lantern_of_power).
card(leokk).
card(lord_slitherspear).
card(mine_cart).
card(mine_shaft).
card(misha).
card(mrglllraawrrrglrur).
card(no_way).
card(pearl_of_the_tides).
card(platemail_armor).
card(power_of_the_titans).
card(putressed).
card(raven_idol).
card(sinister_power).
card(skelesaurus_hex).
card(sun_raider_phaerix).
card(swing_across).
card(take_the_shortcut).
card(temple_escape).
card(temple_escape_enchant).
card(the_steel_sentinel).
card(touch_it).
card(trogg_hate_minions).
card(trogg_hate_spells).
card(trogg_no_stupid).
card(unearthed_raptor).
card(walk_across_gingerly).
card(watched).
card(zinaar).
card(a_glowing_pool).
card(ancient_curse).
card(ancient_power).
card(benediction_splinter).
card(crown_of_kaelthas).
card(djinns_intuition).
card(drink_deeply).
card(endless_hunger).
card(escape).
card(eye_of_orsis).
card(flee_the_mine).
card(getting_hungry).
card(hakkari_blood_goblet).
card(khadgars_pipe).
card(lothars_left_greave).
card(medivhs_locket).
card(mrglmrgl_mrgl).
card(murloc_tinyfin).
card(pit_of_spikes).
card(putress_vial).
card(rod_of_the_sun).
card(rummage).
card(shard_of_sulfuras).
card(the_darkness).
card(the_eye).
card(unstable_portal).
card(wade_through).
card(wish_for_companionship).
card(wish_for_glory).
card(wish_for_more_wishes).
card(wish_for_power).
card(wish_for_valor).
card(yseras_tear).
card(animated_statue).
card(barrel_forward).
card(boom).
card(consult_brann).
card(debris).
card(dynamite).
card(earthen_statue).
card(eye_of_hakkar).
card(hungry_naga).
card(mechanical_parrot).
card(naga_repellent).
card(pit_snake).
card(rare_spear).
card(reliquary_seeker).
card(repairs).
card(rock).
card(sacred_trial).
card(scarab).
card(sir_finley_mrrgglton).
card(spiked_decoy).
card(stonesculpting).
card(throw_rocks).
card(tunnel_trogg).
card(animate_earthen).
card(curse_of_rafaam).
card(cursed).
card(dark_peddler).
card(dart_trap).
card(grumbly_runt).
card(huge_toad).
card(jeweled_scarab).
card(map_to_the_golden_monkey).
card(museum_curator).
card(rascally_runt).
card(shattering_spree).
card(slithering_archer).
card(wily_runt).
card(boneraptor).
card(brann_bronzebeard).
card(desert_camel).
card(fierce_monkey).
card(forgotten_torch).
card(looming_presence).
card(mounted_raptor).
card(mrgl_mrgl_nyah_nyah).
card(mummy_zombie).
card(roaring_torch).
card(tolvir_hoplite).
card(ancient_shade).
card(animated_armor).
card(chasing_trogg).
card(eerie_statue).
card(elise_starseeker).
card(golden_monkey).
card(gorillabot_a-3).
card(jungle_moonkin).
card(keeper_of_uldaman).
card(orsis_guard).
card(rolling_boulder).
card(rumbling_elemental).
card(tomb_pillager).
card(tomb_spider).
card(anubisath_sentinel).
card(djinni_of_zephyrs).
card(earthen_pursuer).
card(ethereal_conjurer).
card(excavated_evil).
card(naga_sea_witch).
card(slithering_guard).
card(summoning_stone).
card(entomb).
card(lumbering_golem).
card(reno_jackson).
card(wobbling_runts).
card(everyfin_is_awesome).
card(giant_insect).
card(obsidian_destroyer).
card(anubisath_temple_guard).
card(fossilized_devilsaur).
card(seething_statue).
card(arch-thief_rafaam).
card(anyfin_can_happen).
card(mirror_of_doom).
card(timepiece_of_horror).
card(system).
card(placeholder_card).
card(naxxramas).
card(baron_rivendare).
card(enrage).
card(extra_teeth).
card(fungal_growth).
card(interloper).
card(loatheb).
card(maexxna).
card(mark_of_the_horsemen).
card(mutating_injection).
card(necrotic_aura).
card(polarity).
card(power_of_the_ziggurat).
card(slave_of_kelthuzad).
card(supercharged).
card(thaddius).
card(vengeance).
card(eruption).
card(frost_blast).
card(frost_breath).
card(mr_bigglesworth).
card(polarity_shift).
card(raise_dead).
card(spore).
card(avenge).
card(deathcharger).
card(jaws).
card(mind_control_crystal).
card(rain_of_fire).
card(skeleton).
card(slime).
card(spectral_spider).
card(spectral_trainee).
card(sporeburst).
card(unbalancing_strike).
card(undertaker).
card(unrelenting_trainee).
card(webspinner).
card(zombie_chow).
card(echoing_ooze).
card(haunted_creeper).
card(mad_scientist).
card(mindpocalypse).
card(necrotic_poison).
card(nerubar_weblord).
card(nerubian).
card(nerubian_egg).
card(reincarnate).
card(skitter).
card(supercharge).
card(understudy).
card(unstable_ghoul).
card(dancing_swords).
card(dark_cultist).
card(deathlord).
card(duplicate).
card(hook).
card(runeblade).
card(shade_of_naxxramas).
card(skeletal_smith).
card(spectral_warrior).
card(stoneskin_gargoyle).
card(thane_korthazz).
card(unrelenting_warrior).
card(worshipper).
card(anubar_ambusher).
card(deaths_bite).
card(deathbloom).
card(guardian_of_icecrown).
card(hateful_strike).
card(necroknight).
card(poison_seeds).
card(voidcaller).
card(wailing_soul).
card(feugen).
card(frozen_champion).
card(pure_cold).
card(sludge_belcher).
card(spectral_knight).
card(spectral_rider).
card(stalagg).
card(unholy_shadow).
card(plague).
card(unrelenting_rider).
card(locust_swarm).
card(chains).
card(blackrock_mountain).
card(blind_with_rage).
card(chromaggus).
card(chromatic_dragonkin).
card(draconic_lineage).
card(draconic_power).
card(dragon_blood).
card(dragons_might).
card(emperor_thaurissan).
card(fire_hawk_form).
card(firecat_form).
card(general_drakkisath).
card(highlord_omokk).
card(imperial_favor).
card(incubation).
card(intense_gaze).
card(large_talons).
card(lava_shock).
card(lord_victor_nefarius).
card(majordomo_executus).
card(maloriak).
card(melt).
card(on_fire).
card(potion_of_might).
card(power_rager).
card(razorgore_the_untamed).
card(rend_blackhand).
card(sonic_breath).
card(the_alchemist).
card(twilight_endurance).
card(unchained).
card(vaelastrasz_the_corrupt).
card(activate_arcanotron).
card(arcanotron).
card(brood_affliction).
card(echolocate).
card(essence_of_the_red).
card(firesworn).
card(ignite_mana).
card(nefarian_strikes).
card(recharge).
card(the_rookery).
card(aberration).
card(black_whelp).
card(blackwing).
card(bone_construct).
card(brood_affliction_black).
card(brood_affliction_blue).
card(brood_affliction_bronze).
card(brood_affliction_green).
card(brood_affliction_red).
card(corrupted_egg).
card(dark_iron_spectator).
card(dragon_egg).
card(dragonkin).
card(dragonteeth).
card(drakkisaths_command).
card(guzzler).
card(magma_pulse).
card(mutation).
card(old_horde_orc).
card(razorgores_claws).
card(reverberating_gong).
card(the_true_warchief).
card(toxitron).
card(true_form).
card(twilight_whelp).
card(activate_toxitron).
card(chromatic_mutation).
card(chromatic_prototype).
card(die_insects).
card(flamewaker_acolyte).
card(gang_up).
card(lava).
card(old_horde).
card(onyxiclaw).
card(power_of_the_firelord).
card(quick_shot).
card(release_the_aberrations).
card(resurrect).
card(revenge).
card(blackwing_technician).
card(demonwrath).
card(druid_of_the_flame).
card(electron).
card(flameheart).
card(flamewaker).
card(get_em).
card(gyth).
card(imp_gang_boss).
card(rock_out).
card(activate_electron).
card(axe_flinger).
card(chromatic_drake).
card(core_rager).
card(dismount).
card(dragonkin_sorcerer).
card(fireguard_destroyer).
card(hungry_dragon).
card(tail_swipe).
card(time_for_smash).
card(blackwing_corruptor).
card(dark_iron_skulker).
card(dragon_consort).
card(dragons_breath).
card(grim_patron).
card(magmatron).
card(magmaw).
card(solemn_vigil).
card(activate_magmatron).
card(dark_iron_bouncer).
card(drakonid_crusher).
card(volcanic_drake).
card(volcanic_lumberer).
card(basic).
card(ancestral_infusion).
card(anduin_wrynn).
card(berserking).
card(blessing_of_kings).
card(blessing_of_might).
card(bloodlust).
card(claw).
card(claws).
card(clerics_blessing).
card(coins_vengeance).
card(coins_vengence).
card(corruption).
card(deadly_poison).
card(divine_spirit).
card(enhanced).
card(eye_in_the_sky).
card(flametongue).
card(frog).
card(frostwolf_banner).
card(furious_howl).
card(garrosh_hellscream).
card(guldan).
card(heroic_strike).
card(hexxed).
card(humility).
card(hunters_mark).
card(luck_of_the_coin).
card(malfurion_stormrage).
card(mark_of_the_wild).
card(masters_presence).
card(might_of_stormwind).
card(mlarggragllabl).
card(polymorph).
card(power_word_shield).
card(rexxar).
card(rockbiter_weapon).
card(savage_roar).
card(the_coin).
card(thrall).
card(totemic_might).
card(uther_lightbringer).
card(ancestral_healing).
card(avatar_of_the_coin).
card(backstab).
card(excess_mana).
card(innervate).
card(mirror_image).
card(sacrificial_pact).
card(arcane_missiles).
card(arcane_shot).
card(boar).
card(elven_archer).
card(frost_shock).
card(goldshire_footman).
card(grimscale_oracle).
card(hand_of_protection).
card(healing_totem).
card(holy_smite).
card(lights_justice).
card(mechanical_dragonling).
card(mind_vision).
card(mortal_coil).
card(murloc_raider).
card(murloc_scout).
card(northshire_cleric).
card(searing_totem).
card(sheep).
card(silver_hand_recruit).
card(sinister_strike).
card(soulfire).
card(stoneclaw_totem).
card(stonetusk_boar).
card(timber_wolf).
card(tracking).
card(voidwalker).
card(voodoo_doctor).
card(whirlwind).
card(wicked_knife).
card(wrath_of_air_totem).
card(acidic_swamp_ooze).
card(arcane_explosion).
card(bloodfen_raptor).
card(bluegill_warrior).
card(dagger_mastery).
card(execute).
card(fiery_war_axe).
card(flametongue_totem).
card(frostbolt).
card(frostwolf_grunt).
card(holy_light).
card(kobold_geomancer).
card(life_tap).
card(mind_blast).
card(murloc_tidehunter).
card(noooooooooooo).
card(novice_engineer).
card(river_crocolisk).
card(sap).
card(shadow_word_pain).
card(shapeshift).
card(shiv).
card(succubus).
card(wild_growth).
card(windfury).
card(animal_companion).
card(arcane_intellect).
card(dalaran_mage).
card(drain_life).
card(fan_of_knives).
card(frost_nova).
card(healing_touch).
card(hex).
card(huffer).
card(ironforge_rifleman).
card(ironfur_grizzly).
card(kill_command).
card(magma_rager).
card(raid_leader).
card(razorfen_hunter).
card(shadow_bolt).
card(shadow_word_death).
card(shattered_sun_cleric).
card(shield_block).
card(silverback_patriarch).
card(warsong_commander).
card(wolfrider).
card(chillwind_yeti).
card(consecration).
card(dragonling_mechanic).
card(fireball).
card(gnomish_inventor).
card(hammer_of_wrath).
card(hellfire).
card(houndmaster).
card(korkron_elite).
card(multi-shot).
card(oasis_snapjaw).
card(ogre_magi).
card(senjin_shieldmasta).
card(stormwind_knight).
card(swipe).
card(truesilver_champion).
card(water_elemental).
card(windspeaker).
card(arcanite_reaper).
card(assassins_blade).
card(assassinate).
card(booty_bay_bodyguard).
card(darkscale_healer).
card(frostwolf_warlord).
card(gurubashi_berserker).
card(holy_nova).
card(nightblade).
card(starving_buzzard).
card(stormpike_commando).
card(tundra_rhino).
card(archmage).
card(boulderfist_ogre).
card(dread_infernal).
card(fire_elemental).
card(lord_of_the_arena).
card(reckless_rocketeer).
card(starfire).
card(vanish).
card(core_hound).
card(flamestrike).
card(guardian_of_kings).
card(sprint).
card(stormwind_champion).
card(war_golem).
card(ironbark_protector).
card(mind_control).
card(debug).
card(onethousand_stats_enchant).
card(again).
card(ai_buddy_-_all_charge_all_windfury).
card(ai_buddy_-_blank_slate).
card(all_charge_all_windfury_all_the_time).
card(empty_enchant).
card(fill_deck).
card(free_cards).
card(molasses).
card(reveal_hand).
card(server_crash).
card(set_all_minions_to_1_health).
card(weapon_buff_enchant).
card(weapon_nerf_enchant).
card(minusone_durability).
card(onethousand_stats).
card(add_1_to_health).
card(add_2_to_health).
card(add_4_to_health).
card(add_8_to_health).
card(ai_buddy_-_all_charge).
card(ai_buddy_-_damage_own_hero_5).
card(ai_buddy_-_destroy_minions).
card(ai_buddy_-_no_deck/hand).
card(ai_helper_buddy).
card(armor_1).
card(armor_100).
card(armor_5).
card(become_hogger).
card(bounce).
card(break_weapon).
card(crash).
card(crash_the_server).
card(damage_1).
card(damage_5).
card(damage_all).
card(damage_all_but_1).
card(damage_reflector).
card(destroy).
card(destroy_a_mana_crystal).
card(destroy_all_heroes).
card(destroy_all_mana).
card(destroy_all_minions).
card(destroy_all_secrets).
card(destroy_deck).
card(destroy_hero_power).
card(destroy_heros_stuff).
card(destroy_target_secrets).
card(discard).
card(do_nothing).
card(draw_3_cards).
card(enable_emotes).
card(enable_for_attack).
card(enchant).
card(force_ai_to_use_hero_power).
card(freeze).
card(grant_mega-windfury).
card(hand_swapper_minion).
card(hand_to_deck).
card(illidan_stormrage_cheat).
card(make_immune).
card(mill_10).
card(mill_30).
card(opponent_concede).
card(opponent_disconnect).
card(remove_all_immune).
card(restore_1).
card(restore_5).
card(restore_all_health).
card(set_health_to_1).
card(set_health_to_full).
card(silence_-_debug).
card(silence_and_destroy_all_minions).
card(snake_ball).
card(steal_card).
card(summon_a_random_secret).
card(the_song_that_ends_the_world).
card(weapon_buff).
card(weapon_nerf).
card(yogg-saron_test_(auto)).
card(yogg-saron_test_(manual)).
card(reward).
card(captains_parrot).
card(old_murk-eye).
card(the_grand_tournament).
card(alexstraszas_boon).
card(boneguarded).
card(bring_it_on).
card(call_of_the_wild).
card(ceremony).
card(chi_lance).
card(competitive_spirit).
card(confused).
card(dark_fusion).
card(dire_claws).
card(dragonhawkery).
card(empowering_mist).
card(experienced).
card(extra_poke).
card(extra_stabby).
card(felrage).
card(fencing_practice).
card(forges_of_orgrimmar).
card(groomed).
card(huge_ego).
card(kindred_spirit).
card(kings_defender).
card(laced).
card(lights_blessing).
card(lion_form).
card(living_roots).
card(lock_and_load).
card(master_summoner).
card(might_of_the_hostler).
card(might_of_the_monkey).
card(mistcaller_deck_ench).
card(panther_form).
card(power_of_dalaran).
card(power_of_the_bluff).
card(power_word_glory).
card(purified).
card(savage).
card(seal_of_champions).
card(shadowfiended).
card(shady_deals).
card(training).
card(training_complete).
card(twilights_embrace).
card(victory).
card(villainy).
card(wound_up).
card(ambush).
card(arcane_blast).
card(brave_archer).
card(buccaneer).
card(flash_heal).
card(gadgetzan_jouster).
card(injured_kvaldir).
card(lowly_squire).
card(poisoned_dagger).
card(sapling).
card(tournament_attendee).
card(alexstraszas_champion).
card(ancestral_knowledge).
card(argent_lance).
card(argent_watchman).
card(bear_trap).
card(bolster).
card(boneguard_lieutenant).
card(confuse).
card(convert).
card(cutpurse).
card(darnassus_aspirant).
card(demonfuse).
card(dire_shapeshift).
card(druid_of_the_saber).
card(fallen_hero).
card(flame_juggler).
card(garrison_commander).
card(kings_elekk).
card(lance_carrier).
card(lightning_jolt).
card(poisoned_daggers).
card(sabertooth_lion).
card(sabertooth_panther).
card(sabertooth_tiger).
card(soul_tap).
card(sparring_partner).
card(tiny_knight_of_evil).
card(totem_golem).
card(undercity_valiant).
card(wrathguard).
card(wyrmrest_agent).
card(argent_horserider).
card(bash).
card(beneath_the_grounds).
card(burgle).
card(coliseum_manager).
card(dragonhawk_rider).
card(dreadscale).
card(effigy).
card(elemental_destruction).
card(eydis_darkbane).
card(fencing_coach).
card(fjola_lightbane).
card(healing_wave).
card(ice_rager).
card(lights_champion).
card(master_of_ceremonies).
card(mulch).
card(orgrimmar_aspirant).
card(polymorph_boar).
card(powershot).
card(saboteur).
card(shadowfiend).
card(shady_dealer).
card(silent_knight).
card(silver_hand_regent).
card(spellslinger).
card(stablemaster).
card(tuskarr_totemic).
card(warhorse_trainer).
card(armored_warhorse).
card(astral_communion).
card(charged_hammer).
card(crowd_favorite).
card(dalaran_aspirant).
card(draenei_totemcarver).
card(dreadsteed).
card(evil_heckler).
card(fist_of_jaraxxus).
card(frigid_snobold).
card(gormok_the_impaler).
card(holy_champion).
card(magnataur_alpha).
card(maiden_of_the_lake).
card(murloc_knight).
card(poisoned_blade).
card(refreshment_vendor).
card(savage_combatant).
card(spawn_of_shadows).
card(tournament_medic).
card(twilight_guardian).
card(wildwalker).
card(clockwork_knight).
card(flame_lance).
card(kvaldir_raider).
card(muklas_champion).
card(nexus-champion_saraad).
card(pit_fighter).
card(ram_wrangler).
card(recruiter).
card(shado-pan_rider).
card(thunder_bluff_valiant).
card(tuskarr_jouster).
card(war_kodo).
card(ball_of_spiders).
card(bolf_ramshield).
card(coldarra_drake).
card(dark_bargain).
card(enter_the_coliseum).
card(grand_crusader).
card(justicar_trueheart).
card(kodorider).
card(master_jouster).
card(mogors_champion).
card(mysterious_challenger).
card(sea_reaver).
card(sideshow_spelleater).
card(the_mistcaller).
card(the_skeleton_knight).
card(void_crusher).
card(wilfred_fizzlebang).
card(acidmaw).
card(captured_jormungar).
card(chillmaw).
card(confessor_paletress).
card(eadric_the_pure).
card(fearsome_doomguard).
card(knight_of_the_wild).
card(skycapn_kragg).
card(rhonin).
card(anubarak).
card(aviana).
card(icehowl).
card(north_sea_kraken).
card(frost_giant).
card(varian_wrynn).
card(goblins_vs_gnomes).
card(armor_plated).
card(armor_plating).
card(attack_mode).
card(brow_furrow).
card(cloaked).
card(dark_wispers).
card(demonheart).
card(extra_sharp).
card(gift_of_cards).
card(gift_of_mana).
card(glaivezooka).
card(grasp_of_malganis).
card(here_take_buff).
card(ironed_out).
card(junked_up).
card(metabolized_magic).
card(metal_teeth).
card(might_of_tinkertown).
card(might_of_zulfarrak).
card(overclocked).
card(pistons).
card(powered).
card(pure).
card(retribution).
card(screwy_jank).
card(seal_of_light).
card(shadowed).
card(shrink_ray).
card(switched).
card(tank_mode).
card(the_king).
card(tinkers_sharpsword_oil).
card(velens_chosen).
card(well_equipped).
card(whirling_blades).
card(burrowing_mine).
card(gallywixs_coin).
card(target_dummy).
card(clockwork_gnome).
card(cogmaster).
card(emergency_coolant).
card(finicky_cloakfield).
card(light_of_the_naaru).
card(reversing_switch).
card(rusty_horn).
card(shadowbomber).
card(time_rewinder).
card(warbot).
card(anodized_robo_cub).
card(call_pet).
card(crackle).
card(darkbomb).
card(explosive_sheep).
card(feign_death).
card(flamecannon).
card(gilblin_stalker).
card(goblin_auto-barber).
card(mechwarper).
card(micro_machine).
card(mistress_of_pain).
card(one-eyed_cheat).
card(puddlestomper).
card(recombobulator).
card(shadowboxer).
card(shielded_minibot).
card(ships_cannon).
card(shrinkmeister).
card(snowchugger).
card(steamwheedle_sniper).
card(stonesplinter_trogg).
card(vitality_totem).
card(whirling_zap-o-matic).
card(bouncing_blade).
card(coghammer).
card(cogmasters_wrench).
card(flying_machine).
card(gnomeregan_infantry).
card(gnomish_experimenter).
card(goblin_sapper).
card(grove_tender).
card(hobgoblin).
card(illuminator).
card(iron_sensei).
card(lil_exorcist).
card(metaltooth_leaper).
card(muster_for_battle).
card(ogre_brute).
card(ogre_warmaul).
card(powermace).
card(scarlet_purifier).
card(soot_spewer).
card(spider_tank).
card(tinkertown_technician).
card(ancestors_call).
card(arcane_nullifier_x-21).
card(burly_rockjaw_trogg).
card(dunemaul_shaman).
card(echo_of_medivh).
card(enhance-o_mechano).
card(fel_cannon).
card(goblin_blastmage).
card(imp-losion).
card(jeeves).
card(kezan_mystic).
card(lost_tallstrider).
card(mechanical_yeti).
card(mini-mage).
card(piloted_shredder).
card(sabotage).
card(screwjank_clunker).
card(siltfin_spiritwalker).
card(wee_spellstopper).
card(antique_healbot).
card(blingtron_3000).
card(bolvar_fordragon).
card(bomb_lobber).
card(cobalt_guardian).
card(cobra_shot).
card(druid_of_the_fang).
card(fel_reaver).
card(floating_watcher).
card(junkbot).
card(king_of_beasts).
card(madder_bomber).
card(mimirons_head).
card(ogre_ninja).
card(quartermaster).
card(salty_dog).
card(siege_engine).
card(upgraded_repair_bot).
card(voljin).
card(anima_golem).
card(gazlowe).
card(iron_juggernaut).
card(lightbomb).
card(mech-bear-cat).
card(mogor_the_ogre).
card(piloted_sky_golem).
card(recycle).
card(shieldmaiden).
card(toshley).
card(trade_prince_gallywix).
card(crush).
card(dr_boom).
card(flame_leviathan).
card(gahzrilla).
card(malorne).
card(neptulon).
card(troggzor_the_earthinator).
card(foe_reaper_4000).
card(force-tank_max).
card(sneeds_old_shredder).
card(v-07-tr-on).
card(malganis).
card(mekgineer_thermaplugg).
card(tree_of_life).
card(clockwork_giant).
card(whispers_of_the_old_gods).
card(addled).
card(amber_carapace).
card(arrakoa_devotion).
card(beacon_of_hope).
card(big_wisps).
card(bloodthistle).
card(briarthorn).
card(caller_devotion).
card(dark_guardian).
card(devotion_of_the_blade).
card(doom_free).
card(embracing_the_shadow).
card(enormous).
card(eve_of_destruction).
card(evolve_scales).
card(evolve_spines).
card(faceless).
card(fadeleaf).
card(fanatic_devotion).
card(flickering_darkness).
card(forbidden_power).
card(geomancy).
card(hour_of_corruption).
card(many_wisps).
card(mark_of_yshaarj).
card(nerubian_spores).
card(new_calling).
card(nights_devotion).
card(optimism).
card(power_of_faith).
card(power_of_the_people).
card(power_transfer).
card(primally_infused).
card(rally).
card(reforged).
card(renounce_darkness_deck_ench).
card(secretly_sated).
card(secrets_of_the_cult).
card(shadowy).
card(shifting).
card(slimed).
card(sorcerous_devotion).
card(soul_power).
card(spines).
card(squid_oil_sheen).
card(tasty).
card(tentacles).
card(terrifying_visage).
card(thirsty_blades).
card(vassals_subservience).
card(will_of_the_vizier).
card(yshaarjs_strength).
card(yogg-sarons_magic).
card(forbidden_flame).
card(forbidden_healing).
card(forbidden_ritual).
card(forbidden_shaping).
card(bladed_cultist).
card(blood_to_ichor).
card(bloodthistle_toxin).
card(briarthorn_toxin).
card(divine_strength).
card(evolve).
card(fadeleaf_toxin).
card(fiery_bat).
card(firebloom_toxin).
card(forbidden_ancient).
card(icky_tentacle).
card(journey_below).
card(kingsblood_toxin).
card(mastiff).
card(nzoths_first_mate).
card(on_the_hunt).
card(ooze).
card(possessed_villager).
card(primal_fusion).
card(rusty_hook).
card(selfless_hero).
card(shadowbeast).
card(shifter_zerus).
card(silver_hand_murloc).
card(spider).
card(tentacle_of_nzoth).
card(vilefin_inquisitor).
card(zealous_initiate).
card(a_light_in_the_darkness).
card(beckoner_of_evil).
card(bilefin_tidehunter).
card(cult_sorcerer).
card(darkshire_librarian).
card(duskboar).
card(embrace_the_shadow).
card(eternal_sentinel).
card(nat_the_darkfisher).
card(renounce_darkness).
card(shatter).
card(stormcrack).
card(the_tidal_hand).
card(twilight_geomancer).
card(twisted_worgen).
card(undercity_huckster).
card(addled_grizzly).
card(amgam_rager).
card(blood_warriors).
card(bloodsail_cultist).
card(carrion_grub).
card(darkshire_councilman).
card(disciple_of_cthun).
card(feral_rage).
card(forlorn_stalker).
card(infest).
card(rallying_blade).
card(ravaging_ghoul).
card(shadow_strike).
card(silithid_swarmer).
card(spawn_of_nzoth).
card(spreading_madness).
card(squirming_tentacle).
card(steward_of_darkshire).
card(twilight_elder).
card(twilight_elemental).
card(twilight_flamecaller).
card(aberrant_berserker).
card(blackwater_pirate).
card(bloodhoof_brave).
card(cthuns_chosen).
card(cyclopian_horror).
card(demented_frostcaller).
card(eater_of_secrets).
card(evolved_kobold).
card(faceless_destroyer).
card(faceless_shambler).
card(fandral_staghelm).
card(flamewreathed_faceless).
card(hooded_acolyte).
card(infested_tauren).
card(infested_wolf).
card(klaxxi_amber-weaver).
card(master_of_evolution).
card(midnight_drake).
card(mire_keeper).
card(polluted_hoarder).
card(shadow_word_horror).
card(shifting_shade).
card(southsea_squidface).
card(twilight_summoner).
card(xaril_poisoned_mind).
card(cabalists_tome).
card(corrupted_healbot).
card(crazed_worshipper).
card(cult_apothecary).
card(darkshire_alchemist).
card(darkspeaker).
card(hallazeal_the_ascended).
card(hammer_of_twilight).
card(power_word_tentacles).
card(princess_huhuran).
card(psych-o-tron).
card(servant_of_yogg-saron).
card(shadowcaster).
card(stand_against_darkness).
card(tentacles_for_arms).
card(twilight_darkmender).
card(usher_of_souls).
card(validated_doomsayer).
card(ancient_harbinger).
card(corrupted_seer).
card(dark_arakkoa).
card(faceless_summoner).
card(herald_volazj).
card(mukla_tyrant_of_the_vale).
card(nerubian_prophet).
card(scaled_nightmare).
card(skeram_cultist).
card(thing_from_below).
card(thistle_tea).
card(ancient_shieldbearer).
card(bog_creeper).
card(chogall).
card(grotesque_dragonhawk).
card(hogger_doom_of_elwynn).
card(malkorok).
card(twin_emperor_veklor).
card(twin_emperor_veknilash).
card(wisps_of_the_old_gods).
card(anomalus).
card(doomcaller).
card(eldritch_horror).
card(giant_sand_worm).
card(nerubian_soldier).
card(ragnaros_lightlord).
card(the_boogeymonster).
card(blade_of_cthun).
card(blood_of_the_ancient_one).
card(soggoth_the_slitherer).
card(the_ancient_one).
card(cthun).
card(deathwing_dragonlord).
card(doom).
card(faceless_behemoth).
card(nzoth_the_corruptor).
card(yshaarj_rage_unbound).
card(yogg-saron_hopes_end).
