value(hemet_nesingwary,2).
value(hogger,4).
value(illidan_stormrage,2).
value(king_mukla,2).
value(lorewalker_cho,1).
value(millhouse_manastorm,1).
value(ancestral_spirit,1).
value(bestial_wrath,1).
value(bite,3).
value(blessed_champion,2).
value(blessing_of_wisdom,3).
value(cold_blood,6).
value(commanding_shout,4).
value(equality,10).
value(far_sight,3).
value(ice_block,10).
value(inner_fire,6).
value(inner_rage,9).
value(mark_of_nature,4).
value(moonfire,6).
value(nourish,7).
value(power_overwhelming,10).
value(preparation,10).
value(rampage,6).
value(repentance,3).
value(shadow_madness,5).
value(soul_of_the_forest,4).
value(starfall,4).
value(wrath,8).
value(circle_of_healing,8).
value(demonfire,2).
value(lord_jaraxxus,9).
value(shadowstep,5).
value(silence,4).
value(wisp,1).
value(abusive_sergeant,7).
value(angry_chicken,1).
value(argent_squire,7).
value(blood_imp,3).
value(bloodsail_corsair,2).
value(conceal,8).
value(dust_devil,3).
value(earth_shock,5).
value(eye_for_an_eye,2).
value(flame_imp,7).
value(forked_lightning,4).
value(hungry_crab,4).
value(ice_lance,6).
value(leper_gnome,4).
value(lightning_bolt,8).
value(lightwarden,3).
value(mana_wyrm,8).
value(murloc_tidecaller,4).
value(naturalize,5).
value(noble_sacrifice,6).
value(redemption,5).
value(savagery,1).
value(secretkeeper,7).
value(shield_slam,9).
value(shieldbearer,1).
value(southsea_deckhand,6).
value(spellbender,3).
value(worgen_infiltrator,6).
value(young_dragonhawk,2).
value(young_priestess,1).
value(amani_berserker,4).
value(ancient_watcher,4).
value(argent_protector,7).
value(armorsmith,6).
value(battle_rage,6).
value(betrayal,5).
value(bloodmage_thalnos,10).
value(bloodsail_raider,6).
value(crazed_alchemist,4).
value(cruel_taskmaster,5).
value(defias_ringleader,6).
value(dire_wolf_alpha,7).
value(doomsayer,7).
value(eviscerate,9).
value(explosive_trap,8).
value(faerie_dragon,6).
value(flare,7).
value(freezing_trap,8).
value(knife_juggler,7).
value(lightwell,3).
value(loot_hoarder,7).
value(mad_bomber,5).
value(mana_addict,2).
value(mana_wraith,1).
value(master_swordsmith,3).
value(misdirection,4).
value(nat_pagle,4).
value(patient_assassin,3).
value(pint-sized_summoner,3).
value(power_of_the_wild,7).
value(scavenging_hyena,5).
value(slam,8).
value(snake_trap,4).
value(snipe,5).
value(sorcerers_apprentice,9).
value(stormforged_axe,1).
value(sunfury_protector,7).
value(wild_pyromancer,7).
value(youthful_brewmaster,6).
value(acolyte_of_pain,8).
value(alarm-o-bot,2).
value(aldor_peacekeeper,9).
value(arcane_golem,3).
value(blood_knight,4).
value(coldlight_oracle,6).
value(coldlight_seer,4).
value(counterspell,6).
value(deadly_shot,7).
value(demolisher,3).
value(divine_favor,5).
value(eaglehorn_bow,9).
value(earthen_ring_farseer,4).
value(edwin_vancleef,10).
value(emperor_cobra,3).
value(felguard,4).
value(feral_spirit,7).
value(flesheating_ghoul,3).
value(frothing_berserker,9).
value(harvest_golem,7).
value(headcrack,3).
value(ice_barrier,8).
value(imp_master,4).
value(injured_blademaster,7).
value(ironbeak_owl,3).
value(jungle_panther,3).
value(kirin_tor_mage,3).
value(lava_burst,7).
value(lightning_storm,6).
value(mana_tide_totem,7).
value(mind_control_tech,3).
value(mirror_entity,5).
value(murloc_warleader,5).
value(perditions_blade,3).
value(questing_adventurer,3).
value(raging_worgen,2).
value(scarlet_crusader,2).
value(sense_demons,1).
value(shadowform,4).
value(si:seven_agent,8).
value(southsea_captain,2).
value(sword_of_justice,4).
value(tauren_warrior,4).
value(thoughtsteal,8).
value(thrallmar_farseer,1).
value(tinkmaster_overspark,1).
value(unbound_elemental,4).
value(unleash_the_hounds,8).
value(vaporize,3).
value(void_terror,3).
value(ancient_brewmaster,3).
value(ancient_mage,1).
value(arathi_weaponsmith,4).
value(auchenai_soulpriest,9).
value(blade_flurry,2).
value(cone_of_cold,3).
value(cult_master,3).
value(dark_iron_dwarf,5).
value(defender_of_argus,7).
value(dread_corsair,6).
value(ethereal_arcanist,7).
value(keeper_of_the_grove,4).
value(lightspawn,3).
value(mass_dispel,2).
value(master_of_disguise,3).
value(mindgames,4).
value(mogushan_warden,1).
value(mortal_strike,4).
value(pit_lord,2).
value(shadowflame,6).
value(silvermoon_guardian,2).
value(spellbreaker,4).
value(twilight_drake,8).
value(violet_teacher,7).
value(abomination,4).
value(azure_drake,9).
value(bane_of_doom,4).
value(big_game_hunter,5).
value(brawl,9).
value(captain_greenskin,1).
value(doomguard,8).
value(doomhammer,9).
value(druid_of_the_claw,6).
value(earth_elemental,4).
value(explosive_shot,3).
value(faceless_manipulator,6).
value(fen_creeper,4).
value(force_of_nature,4).
value(harrison_jones,9).
value(holy_wrath,4).
value(leeroy_jenkins,8).
value(silver_hand_knight,4).
value(spiteful_smith,3).
value(stampeding_kodo,6).
value(stranglethorn_tiger,5).
value(venture_co_mercenary,3).
value(argent_commander,4).
value(avenging_wrath,4).
value(blizzard,8).
value(cabal_shadow_priest,6).
value(cairne_bloodhoof,8).
value(frost_elemental,4).
value(gadgetzan_auctioneer,7).
value(holy_fire,4).
value(kidnapper,2).
value(priestess_of_elune,2).
value(savannah_highmane,9).
value(siphon_soul,6).
value(sunwalker,3).
value(sylvanas_windrunner,10).
value(temple_enforcer,5).
value(the_beast,6).
value(the_black_knight,7).
value(windfury_harpy,3).
value(ancient_of_lore,4).
value(ancient_of_war,6).
value(archmage_antonidas,7).
value(baron_geddon,8).
value(gladiators_longbow,4).
value(gorehowl,9).
value(prophet_velen,5).
value(ravenholdt_assassin,3).
value(alakir_the_windlord,6).
value(grommash_hellscream,9).
value(gruul,2).
value(lay_on_hands,7).
value(ragnaros_the_firelord,9).
value(tirion_fordring,9).
value(twisting_nether,6).
value(alexstrasza,7).
value(cenarius,6).
value(king_krush,5).
value(malygos,7).
value(nozdormu,4).
value(onyxia,6).
value(ysera,8).
value(deathwing,7).
value(pyroblast,7).
value(sea_giant,9).
value(mountain_giant,6).
value(molten_giant,4).
value(elite_tauren_chieftain,2).
value(kindly_grandmother,7).
value(prince_malchezaar,6).
value(silverware_golem,4).
value(arcane_anomaly,3).
value(babbling_book,8).
value(enchanted_raven,6).
value(malchezaars_imp,4).
value(runic_egg,1).
value(spirit_claws,7).
value(swashburglar,8).
value(cat_trick,7).
value(maelstrom_portal,6).
value(medivhs_valet,4).
value(netherspite_historian,7).
value(pompous_thespian,2).
value(purify,1).
value(cloaked_huntress,7).
value(deadly_fork,6).
value(moroes,4).
value(nightbane_templar,4).
value(pantry_spider,2).
value(protect_the_king,5).
value(violet_illusionist,2).
value(zoobot,4).
value(arcanosmith,3).
value(barnes,9).
value(priest_of_the_feast,7).
value(silvermoon_portal,3).
value(wicked_witchdoctor,2).
value(avian_watcher,4).
value(ethereal_peddler,6).
value(fools_bane,3).
value(ironforge_portal,5).
value(kara_kazham,3).
value(menagerie_magician,3).
value(onyx_bishop,7).
value(book_wyrm,6).
value(menagerie_warden,3).
value(moat_lurker,4).
value(moonglade_portal,6).
value(firelands_portal,7).
value(the_curator,6).
value(medivh_the_guardian,8).
value(arcane_giant,9).
value(annoy-o-tron,4).
value(charge,1).
value(kelthuzad,4).
value(dragonkin_spellcaster,3).
value(cursed_blade,1).
value(explorers_hat,3).
value(raven_idol,8).
value(murloc_tinyfin,1).
value(sacred_trial,1).
value(sir_finley_mrrgglton,7).
value(tunnel_trogg,7).
value(curse_of_rafaam,4).
value(dark_peddler,6).
value(dart_trap,4).
value(huge_toad,6).
value(jeweled_scarab,5).
value(museum_curator,7).
value(brann_bronzebeard,6).
value(desert_camel,4).
value(fierce_monkey,7).
value(forgotten_torch,7).
value(mounted_raptor,4).
value(ancient_shade,1).
value(animated_armor,2).
value(eerie_statue,1).
value(elise_starseeker,7).
value(gorillabot_a-3,5).
value(jungle_moonkin,4).
value(keeper_of_uldaman,8).
value(tomb_pillager,7).
value(tomb_spider,5).
value(anubisath_sentinel,4).
value(djinni_of_zephyrs,4).
value(ethereal_conjurer,8).
value(excavated_evil,8).
value(naga_sea_witch,4).
value(summoning_stone,5).
value(entomb,9).
value(reno_jackson,7).
value(wobbling_runts,4).
value(everyfin_is_awesome,4).
value(obsidian_destroyer,4).
value(fossilized_devilsaur,4).
value(arch-thief_rafaam,6).
value(anyfin_can_happen,8).
value(baron_rivendare,2).
value(loatheb,7).
value(maexxna,4).
value(avenge,6).
value(undertaker,2).
value(webspinner,1).
value(zombie_chow,5).
value(echoing_ooze,2).
value(haunted_creeper,6).
value(mad_scientist,7).
value(nerubar_weblord,2).
value(nerubian_egg,6).
value(reincarnate,3).
value(unstable_ghou,6).
value(dancing_swords,3).
value(dark_cultist,7).
value(deathlord,6).
value(duplicate,5).
value(shade_of_naxxramas,6).
value(stoneskin_gargoyle,2).
value(poison_seeds,4).
value(voidcaller,6).
value(wailing_soul,1).
value(feugen,2).
value(sludge_belcher,8).
value(spectral_knight,4).
value(stalagg,2).
value(chromaggus,6).
value(emperor_thaurissan,7).
value(lava_shock,6).
value(majordomo_executus,3).
value(rend_blackhand,3).
value(dragon_egg,2).
value(gang_up,4).
value(quick_shot,7).
value(resurrect,8).
value(revenge,6).
value(blackwing_technician,6).
value(demonwrath,4).
value(druid_of_the_flame,5).
value(flamewaker,8).
value(imp_gang_boss,8).
value(axe_flinger,4).
value(core_rager,3).
value(dragonkin_sorcerer,2).
value(hungry_dragon,2).
value(blackwing_corruptor,6).
value(dark_iron_skulker,5).
value(dragon_consort,5).
value(grim_patron,4).
value(solemn_vigil,6).
value(drakonid_crusher,4).
value(volcanic_drake,3).
value(volcanic_lumberer,3).
value(blessing_of_kings,4).
value(blessing_of_might,6).
value(bloodlust,5).
value(claw,1).
value(corruption,1).
value(deadly_poison,6).
value(divine_spirit,3).
value(heroic_strike,4).
value(humility,4).
value(hunters_mark,4).
value(mark_of_the_wild,6).
value(polymorph,7).
value(power_word_shield,8).
value(rockbiter_weapon,4).
value(savage_roar,5).
value(totemic_might,1).
value(ancestral_healing,1).
value(backstab,10).
value(innervate,10).
value(mirror_image,8).
value(sacrificial_pact,3).
value(arcane_missiles,6).
value(arcane_shot,4).
value(elven_archer,1).
value(frost_shock,2).
value(goldshire_footman,1).
value(grimscale_oracle,1).
value(hand_of_protection,2).
value(holy_smite,4).
value(lights_justice,1).
value(mind_vision,2).
value(mortal_coil,6).
value(northshire_cleric,6).
value(sinister_strike,3).
value(soulfire,6).
value(stonetusk_boar,1).
value(timber_wolf,2).
value(tracking,3).
value(voidwalker,5).
value(voodoo_doctor,2).
value(whirlwind,4).
value(acidic_swamp_ooze,6).
value(arcane_explosion,2).
value(bloodfen_raptor,1).
value(bluegill_warrior,4).
value(execute,8).
value(fiery_war_axe,9).
value(flametongue_totem,9).
value(frostbolt,9).
value(frostwolf_grunt,1).
value(holy_light,2).
value(kobold_geomancer,3).
value(mind_blast,2).
value(murloc_tidehunter,2).
value(novice_engineer,1).
value(river_crocolisk,1).
value(sap,6).
value(shadow_word_pain,7).
value(shiv,4).
value(succubus,3).
value(wild_growth,7).
value(windfury,1).
value(animal_companion,8).
value(arcane_intellect,8).
value(dalaran_mage,1).
value(drain_life,2).
value(fan_of_knives,6).
value(frost_nova,5).
value(healing_touch,2).
value(hex,7).
value(ironforge_rifleman,2).
value(ironfur_grizzly,2).
value(kill_command,6).
value(magma_rager,1).
value(raid_leader,2).
value(razorfen_hunter,1).
value(shadow_bolt,4).
value(shadow_word_death,7).
value(shattered_sun_cleric,5).
value(shield_block,7).
value(silverback_patriarch,1).
value(warsong_commander,1).
value(wolfrider,3).
value(chillwind_yeti,6).
value(consecration,7).
value(dragonling_mechanic,3).
value(fireball,8).
value(gnomish_inventor,1).
value(hammer_of_wrath,3).
value(hellfire,5).
value(houndmaster,5).
value(korkron_elite,6).
value(multi-shot,2).
value(oasis_snapjaw,1).
value(ogre_magi,3).
value(senjin_shieldmasta,5).
value(stormwind_knight,2).
value(swipe,9).
value(truesilver_champion,9).
value(water_elemental,8).
value(windspeaker,2).
value(arcanite_reaper,4).
value(assassins_blade,2).
value(assassinate,3).
value(booty_bay_bodyguard,2).
value(darkscale_healer,2).
value(frostwolf_warlord,4).
value(gurubashi_berserker,4).
value(holy_nova,6).
value(nightblade,3).
value(starving_buzzard,3).
value(stormpike_commando,2).
value(tundra_rhino,4).
value(archmage,3).
value(boulderfist_ogre,5).
value(dread_infernal,4).
value(fire_elemental,7).
value(lord_of_the_arena,3).
value(reckless_rocketeer,3).
value(starfire,3).
value(vanish,4).
value(core_hound,2).
value(flamestrike,8).
value(guardian_of_kings,4).
value(sprint,6).
value(stormwind_champion,5).
value(war_golem,4).
value(ironbark_protector,4).
value(mind_control,6).
value(captains_parrot,1).
value(old_murk-eye,4).
value(call_of_the_wild,8).
value(competitive_spirit,3).
value(confused,2).
value(kings_defender,3).
value(living_roots,7).
value(lock_and_load,4).
value(power_word_glory,2).
value(seal_of_champions,3).
value(arcane_blast,7).
value(brave_archer,1).
value(buccaneer,1).
value(flash_heal,6).
value(gadgetzan_jouster,2).
value(injured_kvaldir,1).
value(lowly_squire,2).
value(poisoned_dagger,1).
value(tournament_attendee,1).
value(alexstraszas_champion,6).
value(ancestral_knowledge,5).
value(argent_lance,4).
value(argent_watchman,2).
value(bear_trap,6).
value(bolster,4).
value(boneguard_lieutenant,3).
value(confuse,2).
value(convert,2).
value(cutpurse,4).
value(darnassus_aspirant,4).
value(demonfuse,2).
value(druid_of_the_saber,3).
value(fallen_hero,5).
value(flame_juggler,6).
value(garrison_commander,5).
value(kings_elekk,7).
value(lance_carrier,3).
value(tiny_knight_of_evil,2).
value(totem_golem,8).
value(undercity_valiant,2).
value(wrathguard,2).
value(wyrmrest_agent,4).
value(argent_horserider,6).
value(bash,7).
value(beneath_the_grounds,4).
value(burgle,6).
value(coliseum_manager,2).
value(dragonhawk_rider,1).
value(dreadscale,2).
value(effigy,4).
value(elemental_destruction,4).
value(eydis_darkbane,3).
value(fencing_coach,2).
value(fjola_lightbane,3).
value(healing_wave,5).
value(ice_rager,2).
value(lights_champion,3).
value(master_of_ceremonies,2).
value(mulch,6).
value(orgrimmar_aspirant,2).
value(polymorph_boar,4).
value(powershot,6).
value(saboteur,2).
value(shadowfiend,3).
value(shady_dealer,4).
value(silent_knight,3).
value(silver_hand_regent,2).
value(spellslinger,3).
value(stablemaster,4).
value(tuskarr_totemic,5).
value(warhorse_trainer,4).
value(armored_warhorse,3).
value(astral_communion,2).
value(charged_hammer,3).
value(crowd_favorite,5).
value(dalaran_aspirant,4).
value(draenei_totemcarver,3).
value(dreadsteed,2).
value(evil_heckler,6).
value(fist_of_jaraxxus,5).
value(frigid_snobold,4).
value(gormok_the_impaler,2).
value(holy_champion,5).
value(magnataur_alpha,3).
value(maiden_of_the_lake,5).
value(murloc_knight,4).
value(poisoned_blade,2).
value(refreshment_vendor,3).
value(savage_combatant,2).
value(spawn_of_shadows,3).
value(tournament_medic,5).
value(twilight_guardian,4).
value(wildwalker,3).
value(clockwork_knight,4).
value(flame_lance,5).
value(kvaldir_raider,4).
value(muklas_champion,3).
value(nexus-champion_saraad,2).
value(pit_fighter,1).
value(ram_wrangler,2).
value(recruiter,5).
value(shado-pan_rider,4).
value(thunder_bluff_valiant,3).
value(tuskarr_jouster,2).
value(war_kodo,3).
value(ball_of_spiders,5).
value(bolf_ramshield,3).
value(coldarra_drake,5).
value(dark_bargain,4).
value(enter_the_coliseum,3).
value(grand_crusader,4).
value(justicar_trueheart,8).
value(kodorider,5).
value(master_jouster,6).
value(mogors_champion,7).
value(mysterious_challenger,9).
value(sea_reaver,3).
value(sideshow_spelleater,5).
value(the_mistcaller,4).
value(the_skeleton_knight,3).
value(void_crusher,5).
value(wilfred_fizzlebang,4).
value(acidmaw,3).
value(captured_jormungar,4).
value(chillmaw,2).
value(confessor_paletress,3).
value(eadric_the_pure,4).
value(fearsome_doomguard,5).
value(knight_of_the_wild,6).
value(skycapn_kragg,5).
value(rhonin,6).
value(anubarak,5).
value(aviana,8).
value(icehowl,6).
value(north_sea_kraken,5).
value(frost_giant,3).
value(varian_wrynn,3).
value(dark_wispers,2).
value(demonheart,3).
value(glaivezooka,3).
value(seal_of_light,4).
value(tinkers_sharpsword_oil,5).
value(velens_chosen,2).
value(target_dummy,3).
value(clockwork_gnome,5).
value(cogmaster,4).
value(light_of_the_naaru,3).
value(shadowbomber,4).
value(warbot,2).
value(anodized_robo_cub,3).
value(call_pet,3).
value(crackle,5).
value(darkbomb,3).
value(explosive_sheep,4).
value(feign_death,5).
value(flamecannon,3).
value(gilblin_stalker,4).
value(goblin_auto-barber,5).
value(mechwarper,4).
value(micro_machine,3).
value(mistress_of_pain,2).
value(one-eyed_cheat,1).
value(puddlestomper,2).
value(recombobulator,3).
value(shadowboxer,4).
value(shielded_minibot,5).
value(ships_cannon,1).
value(shrinkmeister,2).
value(snowchugger,3).
value(steamwheedle_sniper,4).
value(stonesplinter_trogg,5).
value(vitality_totem,1).
value(whirling_zap-o-matic,2).
value(bouncing_blade,3).
value(coghammer,4).
value(cogmasters_wrench,5).
value(flying_machine,4).
value(gnomeregan_infantry,3).
value(gnomish_experimenter,5).
value(goblin_sapper,2).
value(grove_tender,3).
value(hobgoblin,3).
value(illuminator,4).
value(iron_sensei,5).
value(lil_exorcist,5).
value(metaltooth_leaper,4).
value(muster_for_battle,5).
value(ogre_brute,5).
value(ogre_warmaul,2).
value(powermace,2).
value(scarlet_purifier,3).
value(soot_spewer,3).
value(spider_tank,4).
value(tinkertown_technician,5).
value(ancestors_call,5).
value(arcane_nullifier_x-21,4).
value(burly_rockjaw_trogg,3).
value(dunemaul_shaman,4).
value(echo_of_medivh,5).
value(enhance-o_mechano,4).
value(fel_cannon,3).
value(goblin_blastmage,4).
value(imp-losion,8).
value(jeeves,4).
value(kezan_mystic,4).
value(lost_tallstrider,5).
value(mechanical_yeti,7).
value(mini-mage,4).
value(piloted_shredder,9).
value(sabotage,5).
value(screwjank_clunker,6).
value(siltfin_spiritwalker,5).
value(wee_spellstopper,6).
value(antique_healbot,8).
value(blingtron_3000,4).
value(bolvar_fordragon,5).
value(bomb_lobber,2).
value(cobalt_guardian,3).
value(cobra_shot,3).
value(druid_of_the_fang,4).
value(fel_reaver,5).
value(floating_watcher,3).
value(junkbot,3).
value(king_of_beasts,5).
value(madder_bomber,4).
value(mimirons_head,3).
value(ogre_ninja,2).
value(quartermaster,4).
value(salty_dog,2).
value(siege_engine,3).
value(upgraded_repair_bot,4).
value(voljin,4).
value(anima_golem,3).
value(gazlowe,2).
value(iron_juggernaut,3).
value(lightbomb,7).
value(mech-bear-cat,3).
value(mogor_the_ogre,4).
value(piloted_sky_golem,5).
value(recycle,2).
value(shieldmaiden,4).
value(toshley,5).
value(trade_prince_gallywix,4).
value(crush,3).
value(dr_boom,10).
value(flame_leviathan,5).
value(gahzrilla,5).
value(malorne,4).
value(neptulon,4).
value(troggzor_the_earthinator,3).
value(foe_reaper_4000,4).
value(force-tank_max,5).
value(sneeds_old_shredder,4).
value(v-07-tr-on,3).
value(malganis,4).
value(mekgineer_thermaplugg,5).
value(tree_of_life,4).
value(clockwork_giant,3).
value(mark_of_yshaarj,4).
value(forbidden_flame,5).
value(forbidden_healing,7).
value(forbidden_ritual,7).
value(forbidden_shaping,3).
value(bladed_cultist,7).
value(blood_to_ichor,8).
value(divine_strength,5).
value(evolve,10).
value(fiery_bat,6).
value(forbidden_ancient,4).
value(journey_below,5).
value(nzoths_first_mate,3).
value(on_the_hunt,5).
value(possessed_villager,3).
value(primal_fusion,2).
value(selfless_hero,4).
value(shadowbeast,3).
value(shifter_zerus,1).
value(tentacle_of_nzoth,4).
value(vilefin_inquisitor,5).
value(zealous_initiate,6).
value(a_light_in_the_darkness,5).
value(beckoner_of_evil,6).
value(bilefin_tidehunter,5).
value(cult_sorcerer,7).
value(darkshire_librarian,4).
value(duskboar,3).
value(embrace_the_shadow,3).
value(eternal_sentinel,2).
value(nat_the_darkfisher,2).
value(renounce_darkness,4).
value(shatter,3).
value(stormcrack,4).
value(the_tidal_hand,4).
value(twilight_geomancer,3).
value(twisted_worgen,2).
value(undercity_huckster,3).
value(addled_grizzly,4).
value(amgam_rager,2).
value(blood_warriors,3).
value(bloodsail_cultist,4).
value(carrion_grub,2).
value(darkshire_councilman,4).
value(disciple_of_cthun,2).
value(feral_rage,3).
value(forlorn_stalker,4).
value(infest,3).
value(rallying_blade,3).
value(ravaging_ghoul,5).
value(shadow_strike,4).
value(silithid_swarmer,3).
value(spawn_of_nzoth,2).
value(spreading_madness,4).
value(squirming_tentacle,3).
value(steward_of_darkshire,3).
value(twilight_elder,2).
value(twilight_elemental,3).
value(twilight_flamecaller,4).
value(aberrant_berserker,3).
value(blackwater_pirate,5).
value(bloodhoof_brave,2).
value(cthuns_chosen,3).
value(cyclopian_horror,4).
value(demented_frostcaller,4).
value(eater_of_secrets,3).
value(evolved_kobold,2).
value(faceless_destroyer,5).
value(faceless_shambler,4).
value(fandral_staghelm,4).
value(flamewreathed_faceless,3).
value(hooded_acolyte,4).
value(infested_tauren,5).
value(infested_wolf,7).
value(klaxxi_amber-weaver,2).
value(master_of_evolution,3).
value(midnight_drake,2).
value(mire_keeper,5).
value(polluted_hoarder,4).
value(shadow_word_horror,3).
value(shifting_shade,3).
value(southsea_squidface,2).
value(twilight_summoner,3).
value(xaril_poisoned_mind,2).
value(cabalists_tome,7).
value(corrupted_healbot,5).
value(crazed_worshipper,2).
value(cult_apothecary,1).
value(darkshire_alchemist,2).
value(darkspeaker,4).
value(hallazeal_the_ascended,3).
value(hammer_of_twilight,4).
value(power_word_tentacles,3).
value(princess_huhuran,2).
value(psych-o-tron,4).
value(servant_of_yogg-saron,5).
value(shadowcaster,4).
value(stand_against_darkness,4).
value(tentacles_for_arms,3).
value(twilight_darkmender,3).
value(usher_of_souls,2).
value(validated_doomsayer,1).
value(ancient_harbinger,4).
value(corrupted_seer,3).
value(dark_arakkoa,2).
value(faceless_summoner,4).
value(herald_volazj,1).
value(mukla_tyrant_of_the_vale,2).
value(nerubian_prophet,1).
value(scaled_nightmare,3).
value(skeram_cultist,2).
value(thing_from_below,9).
value(thistle_tea,2).
value(ancient_shieldbearer,4).
value(bog_creeper,3).
value(chogall,2).
value(grotesque_dragonhawk,1).
value(hogger_doom_of_elwynn,5).
value(malkorok,4).
value(twin_emperor_veklor,3).
value(twin_emperor_veknilash,2).
value(wisps_of_the_old_gods,5).
value(anomalus,5).
value(doomcaller,4).
value(eldritch_horror,3).
value(giant_sand_worm,2).
value(nerubian_soldier,1).
value(ragnaros_lightlord,7).
value(the_boogeymonster,3).
value(blade_of_cthun,3).
value(blood_of_the_ancient_one,3).
value(soggoth_the_slitherer,7).
value(cthun,7).
value(deathwing_dragonlord,6).
value(doom,4).
value(faceless_behemoth,5).
value(nzoth_the_corruptor,8).
value(yshaarj_rage_unbound,6).
value(yogg-saron_hopes_end,7).
value(dragons_breath,5).


value(X,Y) :-
  value(X),
  member(Y,[1,2,3,4,5,6,7,8,9,10]).

should_craft(X,Y) :-
  value(X,Value1),
  value(Y,Value2),
  ((Value1 < Value2) -> write(Y);
  (Value1 = Value2) -> write("both are equivalent.");write(X)).
