combo(archmage_antonidas,frost_nova).
combo(doomsayer,frost_nova).
combo(doomsayer,blizzard).
combo(ice_block,medivhs_valet).
combo(ice_barrier,medivhs_valet).
combo(counterspell,medivhs_valet).
combo(vaporize,medivhs_valet).
combo(spellbender,medivhs_valet).
combo(mirror_entity,medivhs_valet).
combo(effigy,medivhs_valet).
combo(emperor_thaurissan,alexstrasza).
combo(flamewaker,arcane_missiles).
combo(flamewaker,mirror_image).
combo(mana_wyrm,mirror_image).
combo(frostbolt,ice_lance).

combo(secretkeeper,freezing_trap).
combo(secretkeeper,explosive_trap).
combo(secretkeeper,dart_trap).
combo(secretkeeper,snake_trap).
combo(secretkeeper,cat_trick).
combo(secretkeeper,bear_trap).
combo(secretkeeper,misdirection).
combo(secretkeeper,snipe).
combo(cloaked_huntress,freezing_trap).
combo(cloaked_huntress,explosive_trap).
combo(cloaked_huntress,dart_trap).
combo(cloaked_huntress,snake_trap).
combo(cloaked_huntress,cat_trick).
combo(cloaked_huntress,bear_trap).
combo(cloaked_huntress,misdirection).
combo(cloaked_huntress,snipe).
combo(eaglehorn_bow,freezing_trap).
combo(eaglehorn_bow,explosive_trap).
combo(eaglehorn_bow,dart_trap).
combo(eaglehorn_bow,snake_trap).
combo(eaglehorn_bow,cat_trick).
combo(eaglehorn_bow,bear_trap).
combo(eaglehorn_bow,misdirection).
combo(eaglehorn_bow,snipe).
combo(knife_juggler,unleash_the_hounds).
combo(knife_juggler,snake_trap).
combo(barnes,savannah_highmane).

combo(fandral_staghelm,raven_idol).
combo(fandral_staghelm,living_roots).
combo(fandral_staghelm,druid_of_the_saber).
combo(fandral_staghelm,power_of_the_wild).
combo(fandral_staghelm,wrath).
combo(fandral_staghelm,druid_of_the_flame).
combo(fandral_staghelm,feral_rage).
combo(fandral_staghelm,mark_of_nature).
combo(fandral_staghelm,keeper_of_the_grove).
combo(fandral_staghelm,mire_keeper).
combo(fandral_staghelm,druid_of_the_claw).
combo(fandral_staghelm,nourish).
combo(fandral_staghelm,starfall).
combo(fandral_staghelm,ancient_of_lore).
combo(fandral_staghelm,ancient_of_war).
combo(fandral_staghelm,wisps_of_the_old_gods).
combo(fandral_staghelm,cenarius).
combo(malygos,moonfire).
combo(malygos,living_roots).
combo(malygos,wrath).
combo(malygos,swipe).
combo(malygos,starfall).
combo(malygos,starfire).
combo(living_roots,power_of_the_wild).

combo(equality,wild_pyromancer).
combo(wild_pyromancer,consecration).
combo(equality,consecration).
combo(barnes,ragnaros_lightlord).
combo(barnes,tirion_fordring).
combo(doomsayer,solemn_vigil).
combo(knife_juggler,stand_against_darkness).

combo(priest_of_the_feast,circle_of_healing).
combo(priest_of_the_feast,silence).
combo(priest_of_the_feast,flash_heal).
combo(priest_of_the_feast,power_word_glory).
combo(priest_of_the_feast,holy_smite).
combo(priest_of_the_feast,inner_fire).
combo(priest_of_the_feast,mind_vision).
combo(priest_of_the_feast,power_word_shield).
combo(priest_of_the_feast,divine_spirit).
combo(priest_of_the_feast,mind_blast).
combo(priest_of_the_feast,purify).
combo(priest_of_the_feast,resurrect).
combo(priest_of_the_feast,shadow_word_pain).
combo(priest_of_the_feast,shadow_word_death).
combo(priest_of_the_feast,thoughtsteal).
combo(injured_blademaster,circle_of_healing).
combo(injured_blademaster,power_word_shield).
combo(injured_blademaster,resurrect).
combo(injured_blademaster,onyx_bishop).
combo(divine_spirit,inner_fire).
combo(power_word_shield,inner_fire).

combo(preparation,fan_of_knives).
combo(preparation,burgle).
combo(preparation,eviscerate).
combo(gadgetzan_auctioneer,conceal).
combo(leeroy_jenkins,cold_blood).
combo(backstab,si_seven_agent).
combo(backstab,eviscerate).
combo(leeroy_jenkins,shadowstep).
combo(preparation,sprint).

combo(barnes,flametongue_totem).
combo(barnes,mana_tide_totem).
combo(doomhammer,rockbiter_weapon).
combo(bloodmage_thalnos,spirit_claws).
combo(windfury,rockbiter_weapon).
combo(tunnel_trogg,feral_spirit).
combo(alakir_the_windlord,rockbiter_weapon).

combo(brann_bronzebeard,dark_peddler).
combo(brann_bronzebeard,defender_of_argus).
combo(leeroy_jenkins,power_overwhelming).
combo(doomguard,power_overwhelming).
combo(doomguard,fist_of_jaraxxus).
combo(succubus,fist_of_jaraxxus).
combo(soulfire,fist_of_jaraxxus).
combo(doomguard,silverware_golem).
combo(succubus,silverware_golem).
combo(soulfire,silverware_golem).
combo(malchezaars_imp,doomguard).
combo(malchezaars_imp,succubus).
combo(malchezaars_imp,soulfire).
combo(knife_juggler,possessed_villager).
combo(knife_juggler,forbidden_ritual).
combo(knife_juggler,kara_kazham).
combo(darkshire_councilman,possessed_villager).
combo(darkshire_councilman,forbidden_ritual).

combo(frothing_berserker,whirlwind).
combo(frothing_berserker,inner_rage).
combo(frothing_berserker,cruel_taskmaster).
combo(frothing_berserker,revenge).
combo(frothing_berserker,blood_to_ichor).
combo(frothing_berserker,ravaging_ghoul).
combo(grommash_hellscream,inner_rage).
combo(grommash_hellscream,whirlwind).
combo(grommash_hellscream,blood_to_ichor).
combo(grommash_hellscream,revenge).
combo(grommash_hellscream,cruel_taskmaster).
combo(cthun,ancient_shieldbearer).
combo(grim_patron,ravaging_ghoul).
combo(grim_patron,inner_rage).
combo(grim_patron,cruel_taskmaster).
combo(grim_patron,whirlwind).
combo(grim_patron,revenge).
combo(grim_patron,blood_to_ichor).

combo(barnes,sylvanas_windrunner).
combo(barnes,cairne_bloodhoof).
combo(barnes,infested_tauren).
combo(barnes,emperor_thaurissan).
combo(barnes,bloodmage_thalnos).
combo(barnes,ragnaros_the_firelord).

combo(cthun,cthuns_chosen).
combo(cthun,twin_emperor_veklor).


combo_with(X,Y) :-
  card(X),
  card(Y),
  combo(X,Y).
