compatible(dragons_might,mage).
compatible(ice_block,mage).
compatible(jaina_proudmoore,mage).
compatible(khadgar,mage).
compatible(mana_gorged,mage).
compatible(medivh,mage).
compatible(millhouse_manastorm,mage).
compatible(noth_the_plaguebringer,mage).
compatible(overclocked,mage).
compatible(polymorph,mage).
compatible(power_of_dalaran,mage).
compatible(power_of_the_kirin_tor,mage).
compatible(raw_power,mage).
compatible(second_class_mage,mage).
compatible(shade_of_aran,mage).
compatible(evocation,mage).
compatible(forbidden_flame,mage).
compatible(mirror_image,mage).
compatible(arcane_blast,mage).
compatible(arcane_missiles,mage).
compatible(astral_portal,mage).
compatible(babbling_book,mage).
compatible(ice_lance,mage).
compatible(mage_armor,mage).
compatible(mana_wyrm,mage).
compatible(spellbender,mage).
compatible(arcane_explosion,mage).
compatible(arcane_power,mage).
compatible(archmages_apprentice,mage).
compatible(cult_sorcerer,mage).
compatible(fallen_hero,mage).
compatible(fireblast,mage).
compatible(fireblast_rank_2,mage).
compatible(flamecannon,mage).
compatible(frostbolt,mage).
compatible(medivhs_valet,mage).
compatible(shatter,mage).
compatible(snowchugger,mage).
compatible(sorcerers_apprentice,mage).
compatible(unstable_portal,mage).
compatible(arcane_intellect,mage).
compatible(archmages_insight,mage).
compatible(counterspell,mage).
compatible(duplicate,mage).
compatible(effigy,mage).
compatible(flame_wreath,mage).
compatible(flamewaker,mage).
compatible(forgotten_torch,mage).
compatible(frost_nova,mage).
compatible(ice_barrier,mage).
compatible(kirin_tor_mage,mage).
compatible(mirror_entity,mage).
compatible(mysterious_rune,mage).
compatible(polymorph_boar,mage).
compatible(roaring_torch,mage).
compatible(soot_spewer,mage).
compatible(spellslinger,mage).
compatible(twilight_flamecaller,mage).
compatible(vaporize,mage).
compatible(animated_armor,mage).
compatible(cone_of_cold,mage).
compatible(dalaran_aspirant,mage).
compatible(demented_frostcaller,mage).
compatible(echo_of_medivh,mage).
compatible(ethereal_arcanist,mage).
compatible(fireball,mage).
compatible(goblin_blastmage,mage).
compatible(water_elemental,mage).
compatible(wee_spellstopper,mage).
compatible(cabalists_tome,mage).
compatible(dragons_breath,mage).
compatible(ethereal_conjurer,mage).
compatible(flame_lance,mage).
compatible(servant_of_yogg-saron,mage).
compatible(blizzard,mage).
compatible(coldarra_drake,mage).
compatible(faceless_summoner,mage).
compatible(archmage_antonidas,mage).
compatible(firelands_portal,mage).
compatible(flame_leviathan,mage).
compatible(flamestrike,mage).
compatible(anomalus,mage).
compatible(rhonin,mage).
compatible(placeholder_card,mage).
compatible(pyroblast,mage).

compatible(alexstraszas_boon,warrior).
compatible(armor_plated,warrior).
compatible(berserk,warrior).
compatible(bloodrage,warrior).
compatible(bolstered,warrior).
compatible(charge,warrior).
compatible(charge,warrior).
compatible(commanding_shout,warrior).
compatible(cursed_blade,warrior).
compatible(enraged,warrior).
compatible(forges_of_orgrimmar,warrior).
compatible(garrosh_hellscream,warrior).
compatible(heroic_strike,warrior).
compatible(hogger,warrior).
compatible(inner_rage,warrior).
compatible(magni_bronzebeard,warrior).
compatible(nazra_wildaxe,warrior).
compatible(needs_sharpening,warrior).
compatible(rampage,warrior).
compatible(screwy_jank,warrior).
compatible(second_class_warrior,warrior).
compatible(training_complete,warrior).
compatible(upgraded,warrior).
compatible(whipped_into_shape,warrior).
compatible(burrowing_mine,warrior).
compatible(battle_axe,warrior).
compatible(blood_to_ichor,warrior).
compatible(heavy_axe,warrior).
compatible(nzoths_first_mate,warrior).
compatible(pawn,warrior).
compatible(rusty_hook,warrior).
compatible(scarab,warrior).
compatible(shield_slam,warrior).
compatible(upgrade,warrior).
compatible(warbot,warrior).
compatible(whirlwind,warrior).
compatible(alexstraszas_champion,warrior).
compatible(armor_up,warrior).
compatible(armorsmith,warrior).
compatible(battle_rage,warrior).
compatible(bolster,warrior).
compatible(cleave,warrior).
compatible(cruel_taskmaster,warrior).
compatible(execute,warrior).
compatible(fiery_war_axe,warrior).
compatible(orc_warrior,warrior).
compatible(revenge,warrior).
compatible(slam,warrior).
compatible(slime,warrior).
compatible(sparring_partner,warrior).
compatible(tank_up,warrior).
compatible(the_horde,warrior).
compatible(bash,warrior).
compatible(blood_warriors,warrior).
compatible(bloodsail_cultist,warrior).
compatible(bouncing_blade,warrior).
compatible(fierce_monkey,warrior).
compatible(frothing_berserker,warrior).
compatible(kings_defender,warrior).
compatible(ogre_warmaul,warrior).
compatible(orgrimmar_aspirant,warrior).
compatible(protect_the_king,warrior).
compatible(ravaging_ghoul,warrior).
compatible(shield_block,warrior).
compatible(warsong_commander,warrior).
compatible(arathi_weaponsmith,warrior).
compatible(axe_flinger,warrior).
compatible(bloodhoof_brave,warrior).
compatible(deaths_bite,warrior).
compatible(korkron_elite,warrior).
compatible(magnataur_alpha,warrior).
compatible(mortal_strike,warrior).
compatible(screwjank_clunker,warrior).
compatible(arcanite_reaper,warrior).
compatible(brawl,warrior).
compatible(fools_bane,warrior).
compatible(ironforge_portal,warrior).
compatible(siege_engine,warrior).
compatible(tentacles_for_arms,warrior).
compatible(iron_juggernaut,warrior).
compatible(sea_reaver,warrior).
compatible(shieldmaiden,warrior).
compatible(ancient_shieldbearer,warrior).
compatible(crush,warrior).
compatible(gorehowl,warrior).
compatible(malkorok,warrior).
compatible(obsidian_destroyer,warrior).
compatible(grommash_hellscream,warrior).
compatible(varian_wrynn,warrior).
compatible(alleria_windrunner,hunter).
compatible(bestial_wrath,hunter).
compatible(charge,hunter).
compatible(explorers_hat,hunter).
compatible(eye_in_the_sky,hunter).
compatible(furious_howl,hunter).
compatible(gladiators_longbow_enchantment,hunter).
compatible(glaivezooka,hunter).
compatible(groomed,hunter).
compatible(hemet_nesingwary,hunter).
compatible(hunters_mark,hunter).
compatible(illidan_stormrage,hunter).
compatible(leokk,hunter).
compatible(lock_and_load,hunter).
compatible(masters_presence,hunter).
compatible(metal_teeth,hunter).
compatible(might_of_zulfarrak,hunter).
compatible(misha,hunter).
compatible(power_rager,hunter).
compatible(rexxar,hunter).
compatible(second_class_hunter,hunter).
compatible(the_king,hunter).
compatible(trapped,hunter).
compatible(upgraded,hunter).
compatible(well_fed,hunter).
compatible(arcane_shot,hunter).
compatible(brave_archer,hunter).
compatible(fiery_bat,hunter).
compatible(hound,hunter).
compatible(mastiff,hunter).
compatible(on_the_hunt,hunter).
compatible(snake,hunter).
compatible(spider,hunter).
compatible(timber_wolf,hunter).
compatible(tracking,hunter).
compatible(webspinner,hunter).
compatible(ballista_shot,hunter).
compatible(bear_trap,hunter).
compatible(big_bad_wolf,hunter).
compatible(call_pet,hunter).
compatible(cat_trick,hunter).
compatible(dart_trap,hunter).
compatible(explosive_trap,hunter).
compatible(feign_death,hunter).
compatible(flare,hunter).
compatible(freezing_trap,hunter).
compatible(hyena,hunter).
compatible(kindly_grandmother,hunter).
compatible(kings_elekk,hunter).
compatible(misdirection,hunter).
compatible(quick_shot,hunter).
compatible(scavenging_hyena,hunter).
compatible(shotgun_blast,hunter).
compatible(snake_trap,hunter).
compatible(snipe,hunter).
compatible(steady_shot,hunter).
compatible(steamwheedle_sniper,hunter).
compatible(animal_companion,hunter).
compatible(carrion_grub,hunter).
compatible(cat_in_a_hat,hunter).
compatible(cloaked_huntress,hunter).
compatible(deadly_shot,hunter).
compatible(desert_camel,hunter).
compatible(dreadscale,hunter).
compatible(eaglehorn_bow,hunter).
compatible(forlorn_stalker,hunter).
compatible(huffer,hunter).
compatible(infest,hunter).
compatible(kill_command,hunter).
compatible(metaltooth_leaper,hunter).
compatible(powershot,hunter).
compatible(stablemaster,hunter).
compatible(unleash_the_hounds,hunter).
compatible(core_rager,hunter).
compatible(houndmaster,hunter).
compatible(infested_wolf,hunter).
compatible(multi-shot,hunter).
compatible(cobra_shot,hunter).
compatible(explosive_shot,hunter).
compatible(king_of_beasts,hunter).
compatible(princess_huhuran,hunter).
compatible(ram_wrangler,hunter).
compatible(starving_buzzard,hunter).
compatible(tundra_rhino,hunter).
compatible(ball_of_spiders,hunter).
compatible(savannah_highmane,hunter).
compatible(acidmaw,hunter).
compatible(gahzrilla,hunter).
compatible(gladiators_longbow,hunter).
compatible(giant_sand_worm,hunter).
compatible(call_of_the_wild,hunter).
compatible(king_krush,hunter).
compatible(ancestral_infusion,shaman).
compatible(ancestral_spirit,shaman).
compatible(bloodlust,shaman).
compatible(experienced,shaman).
compatible(far_sight,shaman).
compatible(flametongue,shaman).
compatible(healing_totem,shaman).
compatible(hexxed,shaman).
compatible(lava_shock,shaman).
compatible(morgl_the_oracle,shaman).
compatible(overloading,shaman).
compatible(power_of_the_bluff,shaman).
compatible(powered,shaman).
compatible(rockbiter_weapon,shaman).
compatible(searing_totem,shaman).
compatible(second_class_shaman,shaman).
compatible(stoneclaw_totem,shaman).
compatible(thrall,shaman).
compatible(totemic_might,shaman).
compatible(trogg_no_stupid,shaman).
compatible(wrath_of_air_totem,shaman).
compatible(ancestral_healing,shaman).
compatible(elemental_eruption,shaman).
compatible(dust_devil,shaman).
compatible(earth_shock,shaman).
compatible(evolve,shaman).
compatible(forked_lightning,shaman).
compatible(frost_shock,shaman).
compatible(lightning_bolt,shaman).
compatible(primal_fusion,shaman).
compatible(spirit_claws,shaman).
compatible(tunnel_trogg,shaman).
compatible(ancestral_knowledge,shaman).
compatible(crackle,shaman).
compatible(eternal_sentinel,shaman).
compatible(flametongue_totem,shaman).
compatible(lightning_jolt,shaman).
compatible(maelstrom_portal,shaman).
compatible(reincarnate,shaman).
compatible(spirit_wolf,shaman).
compatible(stormcrack,shaman).
compatible(stormforged_axe,shaman).
compatible(totem_golem,shaman).
compatible(totemic_call,shaman).
compatible(totemic_slam,shaman).
compatible(vitality_totem,shaman).
compatible(whirling_zap-o-matic,shaman).
compatible(windfury,shaman).
compatible(elemental_destruction,shaman).
compatible(feral_spirit,shaman).
compatible(healing_wave,shaman).
compatible(hex,shaman).
compatible(lava_burst,shaman).
compatible(lightning_storm,shaman).
compatible(mana_tide_totem,shaman).
compatible(powermace,shaman).
compatible(tuskarr_totemic,shaman).
compatible(twilight_elemental,shaman).
compatible(unbound_elemental,shaman).
compatible(ancestors_call,shaman).
compatible(charged_hammer,shaman).
compatible(draenei_totemcarver,shaman).
compatible(dunemaul_shaman,shaman).
compatible(fireguard_destroyer,shaman).
compatible(flamewreathed_faceless,shaman).
compatible(master_of_evolution,shaman).
compatible(rumbling_elemental,shaman).
compatible(siltfin_spiritwalker,shaman).
compatible(wicked_witchdoctor,shaman).
compatible(windspeaker,shaman).
compatible(doomhammer,shaman).
compatible(earth_elemental,shaman).
compatible(hallazeal_the_ascended,shaman).
compatible(hammer_of_twilight,shaman).
compatible(thunder_bluff_valiant,shaman).
compatible(fire_elemental,shaman).
compatible(the_mistcaller,shaman).
compatible(thing_from_below,shaman).
compatible(everyfin_is_awesome,shaman).
compatible(neptulon,shaman).
compatible(alakir_the_windlord,shaman).
compatible(anduin_wrynn,priest).
compatible(bring_it_on,priest).
compatible(clerics_blessing,priest).
compatible(confused,priest).
compatible(divine_spirit,priest).
compatible(infusion,priest).
compatible(inner_fire,priest).
compatible(melt,priest).
compatible(mind_controlling,priest).
compatible(power_of_the_ziggurat,priest).
compatible(power_word_shield,priest).
compatible(repairs,priest).
compatible(second_class_priest,priest).
compatible(shadow_madness,priest).
compatible(shadowed,priest).
compatible(shadowfiended,priest).
compatible(tentacles,priest).
compatible(tyrande_whisperwind,priest).
compatible(alms_of_light,priest).
compatible(circle_of_healing,priest).
compatible(forbidden_shaping,priest).
compatible(secrets_of_shadow,priest).
compatible(shadow_of_nothing,priest).
compatible(silence,priest).
compatible(twisted_light,priest).
compatible(flash_heal,priest).
compatible(holy_smite,priest).
compatible(light_of_the_naaru,priest).
compatible(mind_vision,priest).
compatible(northshire_cleric,priest).
compatible(power_word_glory,priest).
compatible(shadowbomber,priest).
compatible(twilight_whelp,priest).
compatible(confuse,priest).
compatible(convert,priest).
compatible(embrace_the_shadow,priest).
compatible(heal,priest).
compatible(lesser_heal,priest).
compatible(lightwell,priest).
compatible(mind_blast,priest).
compatible(mind_shatter,priest).
compatible(mind_spike,priest).
compatible(museum_curator,priest).
compatible(purify,priest).
compatible(resurrect,priest).
compatible(shadow_or_light?,priest).
compatible(shadow_word_pain,priest).
compatible(shadowboxer,priest).
compatible(shrinkmeister,priest).
compatible(wyrmrest_agent,priest).
compatible(dark_cultist,priest).
compatible(shadow_word_death,priest).
compatible(shadowfiend,priest).
compatible(shadowform,priest).
compatible(thoughtsteal,priest).
compatible(velens_chosen,priest).
compatible(auchenai_soulpriest,priest).
compatible(holy_champion,priest).
compatible(hooded_acolyte,priest).
compatible(lightspawn,priest).
compatible(mass_dispel,priest).
compatible(mindgames,priest).
compatible(priest_of_the_feast,priest).
compatible(shadow_word_horror,priest).
compatible(shifting_shade,priest).
compatible(spawn_of_shadows,priest).
compatible(darkshire_alchemist,priest).
compatible(excavated_evil,priest).
compatible(holy_nova,priest).
compatible(onyx_bishop,priest).
compatible(power_word_tentacles,priest).
compatible(twilight_darkmender,priest).
compatible(upgraded_repair_bot,priest).
compatible(voljin,priest).
compatible(cabal_shadow_priest,priest).
compatible(entomb,priest).
compatible(herald_volazj,priest).
compatible(holy_fire,priest).
compatible(lightbomb,priest).
compatible(temple_enforcer,priest).
compatible(confessor_paletress,priest).
compatible(prophet_velen,priest).
compatible(mind_control,priest).
compatible(blood_pact,warlock).
compatible(brow_furrow,warlock).
compatible(consume,warlock).
compatible(corruption,warlock).
compatible(demonheart,warlock).
compatible(felrage,warlock).
compatible(grasp_of_malganis,warlock).
compatible(guldan,warlock).
compatible(heigan_the_unclean,warlock).
compatible(master_summoner,warlock).
compatible(power_of_the_people,warlock).
compatible(power_overwhelming,warlock).
compatible(second_class_warlock,warlock).
compatible(sinister_power,warlock).
compatible(demonfire,warlock).
compatible(forbidden_ritual,warlock).
compatible(lord_jaraxxus,warlock).
compatible(sacrificial_pact,warlock).
compatible(blood_imp,warlock).
compatible(candle,warlock).
compatible(flame_imp,warlock).
compatible(icky_tentacle,warlock).
compatible(imp,warlock).
compatible(malchezaars_imp,warlock).
compatible(mortal_coil,warlock).
compatible(possessed_villager,warlock).
compatible(reliquary_seeker,warlock).
compatible(shadowbeast,warlock).
compatible(soulfire,warlock).
compatible(voidwalker,warlock).
compatible(worthless_imp,warlock).
compatible(broom,warlock).
compatible(curse_of_rafaam,warlock).
compatible(cursed,warlock).
compatible(dark_peddler,warlock).
compatible(darkbomb,warlock).
compatible(darkshire_librarian,warlock).
compatible(demonfuse,warlock).
compatible(inferno,warlock).
compatible(life_tap,warlock).
compatible(mistress_of_pain,warlock).
compatible(renounce_darkness,warlock).
compatible(soul_tap,warlock).
compatible(succubus,warlock).
compatible(tiny_knight_of_evil,warlock).
compatible(wrathguard,warlock).
compatible(blood_fury,warlock).
compatible(darkshire_councilman,warlock).
compatible(demonwrath,warlock).
compatible(drain_life,warlock).
compatible(felguard,warlock).
compatible(imp_gang_boss,warlock).
compatible(sense_demons,warlock).
compatible(shadow_bolt,warlock).
compatible(silverware_golem,warlock).
compatible(spreading_madness,warlock).
compatible(teapot,warlock).
compatible(void_terror,warlock).
compatible(dreadsteed,warlock).
compatible(fel_cannon,warlock).
compatible(fist_of_jaraxxus,warlock).
compatible(hellfire,warlock).
compatible(imp-losion,warlock).
compatible(kilrek,warlock).
compatible(pit_lord,warlock).
compatible(shadowflame,warlock).
compatible(summoning_portal,warlock).
compatible(voidcaller,warlock).
compatible(bane_of_doom,warlock).
compatible(doomguard,warlock).
compatible(floating_watcher,warlock).
compatible(kara_kazham,warlock).
compatible(usher_of_souls,warlock).
compatible(abyssal,warlock).
compatible(anima_golem,warlock).
compatible(dark_bargain,warlock).
compatible(dread_infernal,warlock).
compatible(infernal,warlock).
compatible(siphon_soul,warlock).
compatible(void_crusher,warlock).
compatible(wilfred_fizzlebang,warlock).
compatible(chogall,warlock).
compatible(fearsome_doomguard,warlock).
compatible(twisting_nether,warlock).
compatible(malganis,warlock).
compatible(doom,warlock).
compatible(ancient_secrets,druid).
compatible(ancient_teachings,druid).
compatible(attack_mode,druid).
compatible(bear_form,druid).
compatible(big_wisps,druid).
compatible(cat_form,druid).
compatible(claw,druid).
compatible(claws,druid).
compatible(coalesce_the_moonlight,druid).
compatible(dark_wispers,druid).
compatible(demigods_favor,druid).
compatible(dire_claws,druid).
compatible(dispel,druid).
compatible(drink_the_moonlight,druid).
compatible(evolve_scales,druid).
compatible(evolve_spines,druid).
compatible(fire_hawk_form,druid).
compatible(firecat_form,druid).
compatible(forbidden_power,druid).
compatible(gift_of_cards,druid).
compatible(gift_of_mana,druid).
compatible(kindred_spirit,druid).
compatible(leader_of_the_pack,druid).
compatible(lion_form,druid).
compatible(living_roots,druid).
compatible(malfurion_stormrage,druid).
compatible(many_wisps,druid).
compatible(mark_of_nature,druid).
compatible(mark_of_the_wild,druid).
compatible(mark_of_yshaarj,druid).
compatible(moonfire,druid).
compatible(nerubian_spores,druid).
compatible(nourish,druid).
compatible(panther_form,druid).
compatible(raven_idol,druid).
compatible(rooted,druid).
compatible(savage,druid).
compatible(savage_roar,druid).
compatible(second_class_druid,druid).
compatible(shandos_lesson,druid).
compatible(soul_of_the_forest,druid).
compatible(spines,druid).
compatible(starfall,druid).
compatible(summon_a_panther,druid).
compatible(tank_mode,druid).
compatible(uproot,druid).
compatible(uprooted,druid).
compatible(wrath,druid).
compatible(yshaarjs_strength,druid).
compatible(yogg-sarons_magic,druid).
compatible(excess_mana,druid).
compatible(innervate,druid).
compatible(wisp,druid).
compatible(enchanted_raven,druid).
compatible(forbidden_ancient,druid).
compatible(naturalize,druid).
compatible(sapling,druid).
compatible(savagery,druid).
compatible(treant,druid).
compatible(anodized_robo_cub,druid).
compatible(darnassus_aspirant,druid).
compatible(dire_shapeshift,druid).
compatible(druid_of_the_saber,druid).
compatible(panther,druid).
compatible(power_of_the_wild,druid).
compatible(sabertooth_lion,druid).
compatible(sabertooth_panther,druid).
compatible(sabertooth_tiger,druid).
compatible(shapeshift,druid).
compatible(slime,druid).
compatible(wild_growth,druid).
compatible(addled_grizzly,druid).
compatible(druid_of_the_flame,druid).
compatible(feral_rage,druid).
compatible(grove_tender,druid).
compatible(healing_touch,druid).
compatible(mounted_raptor,druid).
compatible(mulch,druid).
compatible(astral_communion,druid).
compatible(bite,druid).
compatible(fandral_staghelm,druid).
compatible(jungle_moonkin,druid).
compatible(keeper_of_the_grove,druid).
compatible(klaxxi_amber-weaver,druid).
compatible(mire_keeper,druid).
compatible(poison_seeds,druid).
compatible(savage_combatant,druid).
compatible(swipe,druid).
compatible(wildwalker,druid).
compatible(druid_of_the_claw,druid).
compatible(druid_of_the_fang,druid).
compatible(force_of_nature,druid).
compatible(dark_arakkoa,druid).
compatible(mech-bear-cat,druid).
compatible(menagerie_warden,druid).
compatible(moonglade_portal,druid).
compatible(recycle,druid).
compatible(starfire,druid).
compatible(ancient_of_lore,druid).
compatible(ancient_of_war,druid).
compatible(knight_of_the_wild,druid).
compatible(malorne,druid).
compatible(wisps_of_the_old_gods,druid).
compatible(ironbark_protector,druid).
compatible(aviana,druid).
compatible(cenarius,druid).
compatible(tree_of_life,druid).
compatible(volcanic_lumberer,druid).
compatible(cold_blood,rogue).
compatible(concealed,rogue).
compatible(disguised,rogue).
compatible(draw_offensive_play,rogue).
compatible(facilitated,rogue).
compatible(ironed_out,rogue).
compatible(laced,rogue).
compatible(preparation,rogue).
compatible(second_class_rogue,rogue).
compatible(shady_deals,rogue).
compatible(sharpened,rogue).
compatible(squid_oil_sheen,rogue).
compatible(thirsty_blades,rogue).
compatible(unearthed_raptor,rogue).
compatible(valeera_sanguinar,rogue).
compatible(vancleefs_vengeance,rogue).
compatible(ambush,rogue).
compatible(backstab,rogue).
compatible(shadowstep,rogue).
compatible(bladed_cultist,rogue).
compatible(bloodthistle_toxin,rogue).
compatible(briarthorn_toxin,rogue).
compatible(buccaneer,rogue).
compatible(conceal,rogue).
compatible(deadly_poison,rogue).
compatible(defias_bandit,rogue).
compatible(fadeleaf_toxin,rogue).
compatible(firebloom_toxin,rogue).
compatible(journey_below,rogue).
compatible(kingsblood_toxin,rogue).
compatible(pit_snake,rogue).
compatible(poisoned_dagger,rogue).
compatible(sinister_strike,rogue).
compatible(swashburglar,rogue).
compatible(wicked_knife,rogue).
compatible(betrayal,rogue).
compatible(cash_in,rogue).
compatible(cutpurse,rogue).
compatible(dagger_mastery,rogue).
compatible(defias_ringleader,rogue).
compatible(eviscerate,rogue).
compatible(gang_up,rogue).
compatible(goblin_auto-barber,rogue).
compatible(one-eyed_cheat,rogue).
compatible(patient_assassin,rogue).
compatible(poisoned_daggers,rogue).
compatible(sap,rogue).
compatible(sharpen,rogue).
compatible(shiv,rogue).
compatible(undercity_huckster,rogue).
compatible(undercity_valiant,rogue).
compatible(beneath_the_grounds,rogue).
compatible(burgle,rogue).
compatible(cogmasters_wrench,rogue).
compatible(deadly_fork,rogue).
compatible(edwin_vancleef,rogue).
compatible(fan_of_knives,rogue).
compatible(headcrack,rogue).
compatible(iron_sensei,rogue).
compatible(perditions_blade,rogue).
compatible(shadow_strike,rogue).
compatible(shady_dealer,rogue).
compatible(sharp_fork,rogue).
compatible(si7_agent,rogue).
compatible(anubar_ambusher,rogue).
compatible(blade_flurry,rogue).
compatible(master_of_disguise,rogue).
compatible(nerubian,rogue).
compatible(poisoned_blade,rogue).
compatible(ryan_masterson,rogue).
compatible(sabotage,rogue).
compatible(southsea_squidface,rogue).
compatible(tinkers_sharpsword_oil,rogue).
compatible(tomb_pillager,rogue).
compatible(xaril_poisoned_mind,rogue).
compatible(assassins_blade,rogue).
compatible(assassinate,rogue).
compatible(dark_iron_skulker,rogue).
compatible(ethereal_peddler,rogue).
compatible(ogre_ninja,rogue).
compatible(shado-pan_rider,rogue).
compatible(shadowcaster,rogue).
compatible(kidnapper,rogue).
compatible(thistle_tea,rogue).
compatible(trade_prince_gallywix,rogue).
compatible(vanish,rogue).
compatible(sprint,rogue).
compatible(anubarak,rogue).
compatible(blade_of_cthun,rogue).
compatible(blessed_champion,paladin).
compatible(blessing_of_kings,paladin).
compatible(blessing_of_might,paladin).
compatible(blessing_of_wisdom,paladin).
compatible(equality,paladin).
compatible(humility,paladin).
compatible(justice_served,paladin).
compatible(lady_liadrin,paladin).
compatible(might_of_the_hostler,paladin).
compatible(pure,paladin).
compatible(purified,paladin).
compatible(rally,paladin).
compatible(repentance,paladin).
compatible(seal_of_champions,paladin).
compatible(second_class_paladin,paladin).
compatible(stand_down,paladin).
compatible(unchained,paladin).
compatible(uther_lightbringer,paladin).
compatible(vengeance,paladin).
compatible(watched,paladin).
compatible(well_equipped,paladin).
compatible(forbidden_healing,paladin).
compatible(avenge,paladin).
compatible(competitive_spirit,paladin).
compatible(defender,paladin).
compatible(divine_strength,paladin).
compatible(eye_for_an_eye,paladin).
compatible(hand_of_protection,paladin).
compatible(lights_justice,paladin).
compatible(noble_sacrifice,paladin).
compatible(redemption,paladin).
compatible(sacred_trial,paladin).
compatible(selfless_hero,paladin).
compatible(silver_hand_murloc,paladin).
compatible(silver_hand_recruit,paladin).
compatible(vilefin_inquisitor,paladin).
compatible(whelp,paladin).
compatible(a_light_in_the_darkness,paladin).
compatible(argent_lance,paladin).
compatible(argent_protector,paladin).
compatible(holy_light,paladin).
compatible(reinforce,paladin).
compatible(seal_of_light,paladin).
compatible(shielded_minibot,paladin).
compatible(the_silver_hand,paladin).
compatible(the_tidal_hand,paladin).
compatible(aldor_peacekeeper,paladin).
compatible(coghammer,paladin).
compatible(divine_favor,paladin).
compatible(muster_for_battle,paladin).
compatible(nightbane_templar,paladin).
compatible(rallying_blade,paladin).
compatible(scarlet_purifier,paladin).
compatible(steward_of_darkshire,paladin).
compatible(sword_of_justice,paladin).
compatible(warhorse_trainer,paladin).
compatible(consecration,paladin).
compatible(hammer_of_wrath,paladin).
compatible(keeper_of_uldaman,paladin).
compatible(murloc_knight,paladin).
compatible(silvermoon_portal,paladin).
compatible(truesilver_champion,paladin).
compatible(ashbringer,paladin).
compatible(bolvar_fordragon,paladin).
compatible(cobalt_guardian,paladin).
compatible(dragon_consort,paladin).
compatible(holy_wrath,paladin).
compatible(quartermaster,paladin).
compatible(solemn_vigil,paladin).
compatible(stand_against_darkness,paladin).
compatible(tuskarr_jouster,paladin).
compatible(avenging_wrath,paladin).
compatible(enter_the_coliseum,paladin).
compatible(ivory_knight,paladin).
compatible(mysterious_challenger,paladin).
compatible(eadric_the_pure,paladin).
compatible(guardian_of_kings,paladin).
compatible(lay_on_hands,paladin).
compatible(ragnaros_lightlord,paladin).
compatible(tirion_fordring,paladin).
compatible(anyfin_can_happen,paladin).
