contain(face_hunter,hunter_mark,1).
contain(face_hunter,freezing_trap,2).
contain(face_hunter,tracking,2).
contain(face_hunter,snake_trap,1).
contain(face_hunter,unleash_the_hounds,2).
contain(face_hunter,explosive_trap,2).
contain(face_hunter,eaglehorn_bow,2).
contain(face_hunter,argent_squire,2).
contain(face_hunter,secretkeeper,2).
contain(face_hunter,kill_command,2).
contain(face_hunter,leeroy_jenkins,1).
contain(face_hunter,quick_shot,2).
contain(face_hunter,argent_horserider,2).
contain(face_hunter,fiery_bat,1).
contain(face_hunter,kindly_grandmother,2).
contain(face_hunter,cloaked_huntress,2).
contain(face_hunter,cat_trick,2).

contain(malygos_druid,nourish,2).
contain(malygos_druid,malygos,1).
contain(malygos_druid,azure_drake,2).
contain(malygos_druid,wild_growth,2).
contain(malygos_druid,stampeding_kodo,1).
contain(malygos_druid,ragnaros_the_firelord,1).
contain(malygos_druid,innervate,2).
contain(malygos_druid,moonfire,2).
contain(malygos_druid,swipe,2).
contain(malygos_druid,wrath,2).
contain(malygos_druid,emperor_thaurissan,1).
contain(malygos_druid,living_roots,2).
contain(malygos_druid,raven_idol,2).
contain(malygos_druid,jungle_moonkin,1).
contain(malygos_druid,mire_keeper,1).
contain(malygos_druid,fandral_staghelm,1).
contain(malygos_druid,feral_rage,2).
contain(malygos_druid,the_curator,1).

contain(freeze_mage,ice_block,2).
contain(freeze_mage,frost_nova,2).
contain(freeze_mage,frostbolt,2).
contain(freeze_mage,ice_lance,2).
contain(freeze_mage,blizzard,2).
contain(freeze_mage,alexstrasza,1).
contain(freeze_mage,loot_hoarder,2).
contain(freeze_mage,acolyte_of_pain,2).
contain(freeze_mage,novice_engineer,2).
contain(freeze_mage,doomsayer,2).
contain(freeze_mage,arcane_intellect,2).
contain(freeze_mage,fireball,2).
contain(freeze_mage,bloodmage_thalnos,1).
contain(freeze_mage,ice_barrier,2).
contain(freeze_mage,emperor_thaurissan,1).
contain(freeze_mage,forgotten_torch,2).

contain(nzoth_paladin,aldor_peacekeeper,2).
contain(nzoth_paladin,wild_pyromancer,2).
contain(nzoth_paladin,sylvanas_windrunner,1).
contain(nzoth_paladin,spellbreaker,1).
contain(nzoth_paladin,tinkmaster_overspark,1).
contain(nzoth_paladin,youthful_brewmaster,1).
contain(nzoth_paladin,consecration,2).
contain(nzoth_paladin,truesilver_champion,2).
contain(nzoth_paladin,equality,2).
contain(nzoth_paladin,tirion_fordring,1).
contain(nzoth_paladin,acolyte_of_pain,2).
contain(nzoth_paladin,doomsayer,2).
contain(nzoth_paladin,cairne_bloodhoof,1).
contain(nzoth_paladin,harrison_jones,1).
contain(nzoth_paladin,solemn_vigil,2).
contain(nzoth_paladin,emperor_thaurissan,1).
contain(nzoth_paladin,justicar_trueheart,1).
contain(nzoth_paladin,forbidden_healing,1).
contain(nzoth_paladin,infested_tauren,1).
contain(nzoth_paladin,nzoth_the_corruptor,1).
contain(nzoth_paladin,ragnaros_lightlord,1).
contain(nzoth_paladin,barnes,1).

contain(summoner_priest,sylvanas_windrunner,1).
contain(summoner_priest,thoughtsteal,1).
contain(summoner_priest,injured_blademaster,2).
contain(summoner_priest,shadow_word_pain,2).
contain(summoner_priest,holy_smite,2).
contain(summoner_priest,power_word_shield,2).
contain(summoner_priest,shadow_madness,1).
contain(summoner_priest,ragnaros_the_firelord,1).
contain(summoner_priest,shadow_word_death,2).
contain(summoner_priest,holy_nova,1).
contain(summoner_priest,resurrect,2).
contain(summoner_priest,confessor_paletress,1).
contain(summoner_priest,entomb,2).
contain(summoner_priest,excavated_evil,2).
contain(summoner_priest,shadow_word_horror,1).
contain(summoner_priest,bog_creeper,1).
contain(summoner_priest,barnes,1).
contain(summoner_priest,arcane_giant,1).
contain(summoner_priest,priest_of_the_feast,2).
contain(summoner_priest,onyx_bishop,2).

contain(miracle_rogue,edwin_vancleef,1).
contain(miracle_rogue,deadly_poison,1).
contain(miracle_rogue,cold_blood,2).
contain(miracle_rogue,gadgetzan_auctioneer,2).
contain(miracle_rogue,questing_adventurer,2).
contain(miracle_rogue,azure_drake,2).
contain(miracle_rogue,conceal,2).
contain(miracle_rogue,si_seven_agent,2).
contain(miracle_rogue,preparation,2).
contain(miracle_rogue,fan_of_knives,2).
contain(miracle_rogue,eviscerate,2).
contain(miracle_rogue,sap,1).
contain(miracle_rogue,backstab,2).
contain(miracle_rogue,bloodmage_thalnos,1).
contain(miracle_rogue,leeroy_jenkins,1).
contain(miracle_rogue,tomb_pillager,2).
contain(miracle_rogue,shadow_strike,1).

contain(midrange_shaman,lightning_bolt,2).
contain(midrange_shaman,feral_spirit,2).
contain(midrange_shaman,bloodlust,1).
contain(midrange_shaman,hex,2).
contain(midrange_shaman,azure_drake,2).
contain(midrange_shaman,flametongue_totem,2).
contain(midrange_shaman,ragnaros_the_firelord,1).
contain(midrange_shaman,bloodmage_thalnos,1).
contain(midrange_shaman,harrison_jones,1).
contain(midrange_shaman,mana_tide_totem,1).
contain(midrange_shaman,lightning_storm,2).
contain(midrange_shaman,totem_golem,2).
contain(midrange_shaman,thunder_bluff_valiant,2).
contain(midrange_shaman,tunnel_trogg,2).
contain(midrange_shaman,thing_from_below,2).
contain(midrange_shaman,barnes,1).
contain(midrange_shaman,spirit_claws,2).
contain(midrange_shaman,maelstrom_portal,2).

contain(renolock,sylvanas_windrunner,1).
contain(renolock,mortal_coil,1).
contain(renolock,big_game_hunter,1).
contain(renolock,acidic_swamp_ooze,1).
contain(renolock,hellfire,1).
contain(renolock,power_overwhelming,1).
contain(renolock,youthful_brewmaster,1).
contain(renolock,alexstrasza,1).
contain(renolock,sunfury_protector,1).
contain(renolock,loot_hoarder,1).
contain(renolock,faceless_manipulator,1).
contain(renolock,doomsayer,1).
contain(renolock,ragnaros_the_firelord,1).
contain(renolock,defender_of_argus,1).
contain(renolock,earthen_ring_farseer,1).
contain(renolock,siphon_soul,1).
contain(renolock,harrison_jones,1).
contain(renolock,shadow_bolt,1).
contain(renolock,shadowflame,1).
contain(renolock,leeroy_jenkins,1).
contain(renolock,imp_gang_boss,1).
contain(renolock,emperor_thaurissan,1).
contain(renolock,demonwrath,1).
contain(renolock,brann_bronzebeard,1).
contain(renolock,reno_jackson,1).
contain(renolock,dark_peddler,1).
contain(renolock,infested_tauren,1).
contain(renolock,nzoth_the_corruptor,1).
contain(renolock,cult_apothecary,1).
contain(renolock,prince_malchezaar,1).

contain(dragon_warrior,frothing_berserker,2).
contain(dragon_warrior,korkron_elite,2).
contain(dragon_warrior,faerie_dragon,2).
contain(dragon_warrior,slam,2).
contain(dragon_warrior,execute,2).
contain(dragon_warrior,azure_drake,2).
contain(dragon_warrior,ragnaros_the_firelord,1).
contain(dragon_warrior,fiery_war_axe,2).
contain(dragon_warrior,grommash_hellscream,1).
contain(dragon_warrior,blackwing_corruptor,2).
contain(dragon_warrior,drakonid_crusher,2).
contain(dragon_warrior,alexstrasza_champion,2).
contain(dragon_warrior,twilight_guardian,2).
contain(dragon_warrior,sir_finley_mrrgglton,1).
contain(dragon_warrior,nzoths_first_mate,1).
contain(dragon_warrior,ravaging_ghoul,2).
contain(dragon_warrior,blood_to_ichor,2).

contain_with(X,Y) :-
  deck_name(X),
  card(Y),
  ((Z is 1);(Z is 2)),
  contain(X,Y,Z).
