deck_name(face_hunter).
deck_name(malygos_druid).
deck_name(freeze_mage).
deck_name(nzoth_paladin).
deck_name(summoner_priest).
deck_name(miracle_rogue).
deck_name(midrange_shaman).
deck_name(renolock).
deck_name(dragon_warrior).
