contain(face_hunter,hunter_mark,1).
contain(face_hunter,freezing_trap,2).
contain(face_hunter,tracking,2).
contain(face_hunter,snake_trap,1).
contain(face_hunter,unleash_the_hounds,2).
contain(face_hunter,explosive_trap,2).
contain(face_hunter,eaglehorn_bow,2).
contain(face_hunter,argent_squire,2).
contain(face_hunter,secretkeeper,2).
contain(face_hunter,kill_command,2).
contain(face_hunter,leeroy_jenkins,1).
contain(face_hunter,quick_shot,2).
contain(face_hunter,argent_horserider,2).
contain(face_hunter,fiery_bat,1).
contain(face_hunter,kindly_grandmother,2).
contain(face_hunter,cloaked_huntress,2).
contain(face_hunter,cat_trick,2).

contain(malygos_druid,nourish,2).
contain(malygos_druid,malygos,1).
contain(malygos_druid,azure_drake,2).
contain(malygos_druid,wild_growth,2).
contain(malygos_druid,stampeding_kodo,1).
contain(malygos_druid,ragnaros_the_firelord,1).
contain(malygos_druid,innervate,2).
contain(malygos_druid,moonfire,2).
contain(malygos_druid,swipe,2).
contain(malygos_druid,wrath,2).
contain(malygos_druid,emperor_thaurissan,1).
contain(malygos_druid,living_roots,2).
contain(malygos_druid,raven_idol,2).
contain(malygos_druid,jungle_moonkin,1).
contain(malygos_druid,mire_keeper,1).
contain(malygos_druid,fandral_staghelm,1).
contain(malygos_druid,feral_rage,2).
contain(malygos_druid,the_curator,1).

contain(freeze_mage,ice_block,2).
contain(freeze_mage,frost_nova,2).
contain(freeze_mage,frostbolt,2).
contain(freeze_mage,ice_lance,2).
contain(freeze_mage,blizzard,2).
contain(freeze_mage,alexstrasza,1).
contain(freeze_mage,loot_hoarder,2).
contain(freeze_mage,acolyte_of_pain,2).
contain(freeze_mage,novice_engineer,2).
contain(freeze_mage,doomsayer,2).
contain(freeze_mage,arcane_intellect,2).
contain(freeze_mage,fireball,2).
contain(freeze_mage,bloodmage_thalnos,1).
contain(freeze_mage,ice_barrier,2).
contain(freeze_mage,emperor_thaurissan,1).
contain(freeze_mage,forgotten_torch,2).

contain(nzoth_paladin,aldor_peacekeeper,2).
contain(nzoth_paladin,wild_pyromancer,2).
contain(nzoth_paladin,sylvanas_windrunner,1).
contain(nzoth_paladin,spellbreaker,1).
contain(nzoth_paladin,tinkmaster_overspark,1).
contain(nzoth_paladin,youthful_brewmaster,1).
contain(nzoth_paladin,consecration,2).
contain(nzoth_paladin,truesilver_champion,2).
contain(nzoth_paladin,equality,2).
contain(nzoth_paladin,tirion_fordring,1).
contain(nzoth_paladin,acolyte_of_pain,2).
contain(nzoth_paladin,doomsayer,2).
contain(nzoth_paladin,cairne_bloodhoof,1).
contain(nzoth_paladin,harrison_jones,1).
contain(nzoth_paladin,solemn_vigil,2).
contain(nzoth_paladin,emperor_thaurissan,1).
contain(nzoth_paladin,justicar_trueheart,1).
contain(nzoth_paladin,forbidden_healing,1).
contain(nzoth_paladin,infested_tauren,1).
contain(nzoth_paladin,nzoth_the_corruptor,1).
contain(nzoth_paladin,ragnaros_lightlord,1).
contain(nzoth_paladin,barnes,1).

contain(summoner_priest,sylvanas_windrunner,1).
contain(summoner_priest,thoughtsteal,1).
contain(summoner_priest,injured_blademaster,2).
contain(summoner_priest,shadow_word_pain,2).
contain(summoner_priest,holy_smite,2).
contain(summoner_priest,power_word_shield,2).
contain(summoner_priest,shadow_madness,1).
contain(summoner_priest,ragnaros_the_firelord,1).
contain(summoner_priest,shadow_word_death,2).
contain(summoner_priest,holy_nova,1).
contain(summoner_priest,resurrect,2).
contain(summoner_priest,confessor_paletress,1).
contain(summoner_priest,entomb,2).
contain(summoner_priest,excavated_evil,2).
contain(summoner_priest,shadow_word_horror,1).
contain(summoner_priest,bog_creeper,1).
contain(summoner_priest,barnes,1).
contain(summoner_priest,arcane_giant,1).
contain(summoner_priest,priest_of_the_feast,2).
contain(summoner_priest,onyx_bishop,2).

contain(miracle_rogue,edwin_vancleef,1).
contain(miracle_rogue,deadly_poison,1).
contain(miracle_rogue,cold_blood,2).
contain(miracle_rogue,gadgetzan_auctioneer,2).
contain(miracle_rogue,questing_adventurer,2).
contain(miracle_rogue,azure_drake,2).
contain(miracle_rogue,conceal,2).
contain(miracle_rogue,si_seven_agent,2).
contain(miracle_rogue,preparation,2).
contain(miracle_rogue,fan_of_knives,2).
contain(miracle_rogue,eviscerate,2).
contain(miracle_rogue,sap,1).
contain(miracle_rogue,backstab,2).
contain(miracle_rogue,bloodmage_thalnos,1).
contain(miracle_rogue,leeroy_jenkins,1).
contain(miracle_rogue,tomb_pillager,2).
contain(miracle_rogue,shadow_strike,1).

contain(midrange_shaman,lightning_bolt,2).
contain(midrange_shaman,feral_spirit,2).
contain(midrange_shaman,bloodlust,1).
contain(midrange_shaman,hex,2).
contain(midrange_shaman,azure_drake,2).
contain(midrange_shaman,flametongue_totem,2).
contain(midrange_shaman,ragnaros_the_firelord,1).
contain(midrange_shaman,bloodmage_thalnos,1).
contain(midrange_shaman,harrison_jones,1).
contain(midrange_shaman,mana_tide_totem,1).
contain(midrange_shaman,lightning_storm,2).
contain(midrange_shaman,totem_golem,2).
contain(midrange_shaman,thunder_bluff_valiant,2).
contain(midrange_shaman,tunnel_trogg,2).
contain(midrange_shaman,thing_from_below,2).
contain(midrange_shaman,barnes,1).
contain(midrange_shaman,spirit_claws,2).
contain(midrange_shaman,maelstrom_portal,2).

contain(renolock,sylvanas_windrunner,1).
contain(renolock,mortal_coil,1).
contain(renolock,big_game_hunter,1).
contain(renolock,acidic_swamp_ooze,1).
contain(renolock,hellfire,1).
contain(renolock,power_overwhelming,1).
contain(renolock,youthful_brewmaster,1).
contain(renolock,alexstrasza,1).
contain(renolock,sunfury_protector,1).
contain(renolock,loot_hoarder,1).
contain(renolock,faceless_manipulator,1).
contain(renolock,doomsayer,1).
contain(renolock,ragnaros_the_firelord,1).
contain(renolock,defender_of_argus,1).
contain(renolock,earthen_ring_farseer,1).
contain(renolock,siphon_soul,1).
contain(renolock,harrison_jones,1).
contain(renolock,shadow_bolt,1).
contain(renolock,shadowflame,1).
contain(renolock,leeroy_jenkins,1).
contain(renolock,imp_gang_boss,1).
contain(renolock,emperor_thaurissan,1).
contain(renolock,demonwrath,1).
contain(renolock,brann_bronzebeard,1).
contain(renolock,reno_jackson,1).
contain(renolock,dark_peddler,1).
contain(renolock,infested_tauren,1).
contain(renolock,nzoth_the_corruptor,1).
contain(renolock,cult_apothecary,1).
contain(renolock,prince_malchezaar,1).

contain(dragon_warrior,frothing_berserker,2).
contain(dragon_warrior,korkron_elite,2).
contain(dragon_warrior,faerie_dragon,2).
contain(dragon_warrior,slam,2).
contain(dragon_warrior,execute,2).
contain(dragon_warrior,azure_drake,2).
contain(dragon_warrior,ragnaros_the_firelord,1).
contain(dragon_warrior,fiery_war_axe,2).
contain(dragon_warrior,grommash_hellscream,1).
contain(dragon_warrior,blackwing_corruptor,2).
contain(dragon_warrior,drakonid_crusher,2).
contain(dragon_warrior,alexstrasza_champion,2).
contain(dragon_warrior,twilight_guardian,2).
contain(dragon_warrior,sir_finley_mrrgglton,1).
contain(dragon_warrior,nzoths_first_mate,1).
contain(dragon_warrior,ravaging_ghoul,2).
contain(dragon_warrior,blood_to_ichor,2).

contain(beast_driud,power_of_the_wild,2).
contain(beast_driud,azure_drake,2).
contain(beast_driud,savage_roar,1).
contain(beast_driud,stranglethorn_tiger,2).
contain(beast_driud,jungle_panther,1).
contain(beast_driud,innervate,2).
contain(beast_driud,druid_of_the_claw,1).
contain(beast_driud,swipe,2).
contain(beast_driud,wrath,2).
contain(beast_driud,savage_combatant,2).
contain(beast_driud,druid_of_the_saber,2).
contain(beast_driud,living_roots,2).
contain(beast_driud,mounted_raptor,2).
contain(beast_driud,mark_of_yshaarj,2).
contain(beast_driud,the_curator,1).
contain(beast_driud,enchanted_raven,2).
contain(beast_driud,menagerie_warden,2).

contain(token_driud,nourish,1).
contain(token_driud,power_of_the_wild,2).
contain(token_driud,ancient_of_war,1).
contain(token_driud,azure_drake,2).
contain(token_driud,wild_growth,2).
contain(token_driud,onyxia,1).
contain(token_driud,violet_teacher,2).
contain(token_driud,innervate,2).
contain(token_driud,druid_of_the_claw,2).
contain(token_driud,cenarius,1).
contain(token_driud,swipe,2).
contain(token_driud,wrath,2).
contain(token_driud,living_roots,2).
contain(token_driud,mulch,1).
contain(token_driud,raven_idol,2).
contain(token_driud,mire_keeper,1).
contain(token_driud,fandral_staghelm,1).
contain(token_driud,moonglade_portal,2).

contain(secret_hunter,savannah_highmane,2).
contain(secret_hunter,freezing_trap,2).
contain(secret_hunter,tracking,1).
contain(secret_hunter,snake_trap,1).
contain(secret_hunter,azure_drake,2).
contain(secret_hunter,explosive_trap,2).
contain(secret_hunter,eaglehorn_bow,2).
contain(secret_hunter,secretkeeper,2).
contain(secret_hunter,ragnaros_the_firelord,1).
contain(secret_hunter,snipe,2).
contain(secret_hunter,animal_companion,2).
contain(secret_hunter,crazed_alchemist,1).
contain(secret_hunter,flare,1).
contain(secret_hunter,quick_shot,2).
contain(secret_hunter,call_of_the_wild,1).
contain(secret_hunter,barnes,1).
contain(secret_hunter,the_curator,1).
contain(secret_hunter,cloaked_huntress,2).
contain(secret_hunter,cat_trick,2).

contain(midrange_hunter,savannah_highmane,2).
contain(midrange_hunter,tundra_rhino,1).
contain(midrange_hunter,houndmaster,2).
contain(midrange_hunter,unleash_the_hounds,2).
contain(midrange_hunter,eaglehorn_bow,2).
contain(midrange_hunter,knife_juggler,1).
contain(midrange_hunter,kill_command,2).
contain(midrange_hunter,animal_companion,2).
contain(midrange_hunter,quick_shot,2).
contain(midrange_hunter,kings_elekk,2).
contain(midrange_hunter,huge_toad,2).
contain(midrange_hunter,nzoth_the_corruptor,1).
contain(midrange_hunter,call_of_the_wild,2).
contain(midrange_hunter,fiery_bat,2).
contain(midrange_hunter,infested_wolf,2).
contain(midrange_hunter,kindly_grandmother,2).
contain(midrange_hunter,barnes,1).

contain(tempo_mage,sorcerers_apprentice,2).
contain(tempo_mage,mirror_image,2).
contain(tempo_mage,flamestrike,1).
contain(tempo_mage,frostbolt,2).
contain(tempo_mage,mana_wyrm,2).
contain(tempo_mage,water_elemental,2).
contain(tempo_mage,azure_drake,2).
contain(tempo_mage,arcane_intellect,2).
contain(tempo_mage,fireball,2).
contain(tempo_mage,bloodmage_thalnos,1).
contain(tempo_mage,arcane_missiles,2).
contain(tempo_mage,flamewaker,2).
contain(tempo_mage,arcane_blast,2).
contain(tempo_mage,forgotten_torch,2).
contain(tempo_mage,yogg-saron_hopes_end,1).
contain(tempo_mage,cult_sorcerer,2).
contain(tempo_mage,firelands_portal,1).

contain(control_mage,sylvanas_windrunner,1).
contain(control_mage,flamestrike,1).
contain(control_mage,frostbolt,2).
contain(control_mage,water_elemental,2).
contain(control_mage,arcane_intellect,1).
contain(control_mage,fireball,2).
contain(control_mage,mirror_entity,1).
contain(control_mage,arcane_missiles,1).
contain(control_mage,polymorph,1).
contain(control_mage,unstable_portal,1).
contain(control_mage,flame_juggler,1).
contain(control_mage,rhonin,1).
contain(control_mage,jeweled_scarab,1).
contain(control_mage,forgotten_torch,2).
contain(control_mage,forbidden_flame,1).
contain(control_mage,cabalists_tome,2).
contain(control_mage,faceless_summoner,2).
contain(control_mage,twilight_flamecaller,2).
contain(control_mage,babbling_book,2).
contain(control_mage,medivh_the_guardian,1).
contain(control_mage,medivhs_valet,1).
contain(control_mage,arcane_giant,1).

contain(dragon_paladin,aldor_peacekeeper,2).
contain(dragon_paladin,consecration,1).
contain(dragon_paladin,azure_drake,2).
contain(dragon_paladin,truesilver_champion,2).
contain(dragon_paladin,equality,1).
contain(dragon_paladin,tirion_fordring,1).
contain(dragon_paladin,acolyte_of_pain,1).
contain(dragon_paladin,ysera,1).
contain(dragon_paladin,blackwing_technician,2).
contain(dragon_paladin,blackwing_corruptor,2).
contain(dragon_paladin,dragon_consort,2).
contain(dragon_paladin,solemn_vigil,1).
contain(dragon_paladin,emperor_thaurissan,1).
contain(dragon_paladin,chillmaw,1).
contain(dragon_paladin,brann_bronzebeard,1).
contain(dragon_paladin,forbidden_healing,1).
contain(dragon_paladin,ragnaros_lightlord,1).
contain(dragon_paladin,scaled_nightmare,2).
contain(dragon_paladin,ivory_knight,1).
contain(dragon_paladin,netherspite_historian,1).
contain(dragon_paladin,nightbane_templar,1).
contain(dragon_paladin,silvermoon_portal,2).

contain(dragon_priest,faerie_dragon,2).
contain(dragon_priest,azure_drake,2).
contain(dragon_priest,shadow_word_pain,1).
contain(dragon_priest,power_word_shield,2).
contain(dragon_priest,shadow_word_death,2).
contain(dragon_priest,holy_nova,2).
contain(dragon_priest,blackwing_technician,2).
contain(dragon_priest,rend_blackhand,1).
contain(dragon_priest,blackwing_corruptor,2).
contain(dragon_priest,nefarian,1).
contain(dragon_priest,drakonid_crusher,1).
contain(dragon_priest,chromaggus,1).
contain(dragon_priest,twilight_whelp,2).
contain(dragon_priest,wyrmrest_agent,2).
contain(dragon_priest,brann_bronzebeard,1).
contain(dragon_priest,entomb,2).
contain(dragon_priest,book_wyrm,1).
contain(dragon_priest,moroes,1).
contain(dragon_priest,netherspite_historian,2).

contain(nzoth_rogue,sylvanas_windrunner,1).
contain(nzoth_rogue,deadly_poison,1).
contain(nzoth_rogue,shiv,1).
contain(nzoth_rogue,si:seven_agent,1).
contain(nzoth_rogue,fan_of_knives,1).
contain(nzoth_rogue,eviscerate,1).
contain(nzoth_rogue,sap,1).
contain(nzoth_rogue,harvest_golem,1).
contain(nzoth_rogue,loot_hoarder,1).
contain(nzoth_rogue,backstab,1).
contain(nzoth_rogue,bloodmage_thalnos,1).
contain(nzoth_rogue,shadowstep,1).
contain(nzoth_rogue,earthen_ring_farseer,1).
contain(nzoth_rogue,assassinate,1).
contain(nzoth_rogue,dark_iron_skulker,1).
contain(nzoth_rogue,burgle,1).
contain(nzoth_rogue,refreshment_vendor,1).
contain(nzoth_rogue,brann_bronzebeard,1).
contain(nzoth_rogue,huge_toad,1).
contain(nzoth_rogue,unearthed_raptor,1).
contain(nzoth_rogue,reno_jackson,1).
contain(nzoth_rogue,tomb_pillager,1).
contain(nzoth_rogue,infested_tauren,1).
contain(nzoth_rogue,nzoth_the_corruptor,1).
contain(nzoth_rogue,undercity_huckster,1).
contain(nzoth_rogue,journey_below,1).
contain(nzoth_rogue,shadow_strike,1).
contain(nzoth_rogue,barnes,1).
contain(nzoth_rogue,ethereal_peddler,1).
contain(nzoth_rogue,swashburglar,1).

contain(malygos_rogue,gadgetzan_auctioneer,2).
contain(malygos_rogue,shiv,2).
contain(malygos_rogue,sinister_strike,2).
contain(malygos_rogue,malygos,1).
contain(malygos_rogue,azure_drake,2).
contain(malygos_rogue,si:seven_agent,2).
contain(malygos_rogue,preparation,2).
contain(malygos_rogue,fan_of_knives,2).
contain(malygos_rogue,eviscerate,2).
contain(malygos_rogue,sap,2).
contain(malygos_rogue,backstab,2).
contain(malygos_rogue,bloodmage_thalnos,1).
contain(malygos_rogue,earthen_ring_farseer,2).
contain(malygos_rogue,emperor_thaurissan,1).
contain(malygos_rogue,tomb_pillager,2).
contain(malygos_rogue,shadow_strike,1).
contain(malygos_rogue,barnes,1).
contain(malygos_rogue,swashburglar,1).

contain(aggro_shaman,lightning_bolt,2).
contain(aggro_shaman,worgen_infiltrator,2).
contain(aggro_shaman,doomhammer,2).
contain(aggro_shaman,feral_spirit,2).
contain(aggro_shaman,flametongue_totem,2).
contain(aggro_shaman,argent_squire,2).
contain(aggro_shaman,rockbiter_weapon,2).
contain(aggro_shaman,lava_burst,2).
contain(aggro_shaman,lava_shock,1).
contain(aggro_shaman,totem_golem,2).
contain(aggro_shaman,argent_horserider,2).
contain(aggro_shaman,ancestral_knowledge,2).
contain(aggro_shaman,sir_finley_mrrgglton,1).
contain(aggro_shaman,tunnel_trogg,2).
contain(aggro_shaman,flamewreathed_faceless,2).
contain(aggro_shaman,eternal_sentinel,2).

contain(evolve_shaman,lightning_bolt,1).
contain(evolve_shaman,feral_spirit,1).
contain(evolve_shaman,bloodlust,1).
contain(evolve_shaman,hex,2).
contain(evolve_shaman,azure_drake,2).
contain(evolve_shaman,flametongue_totem,2).
contain(evolve_shaman,mana_tide_totem,2).
contain(evolve_shaman,tuskarr_totemic,2).
contain(evolve_shaman,ancestral_knowledge,2).
contain(evolve_shaman,tunnel_trogg,2).
contain(evolve_shaman,thing_from_below,2).
contain(evolve_shaman,master_of_evolution,1).
contain(evolve_shaman,bilefin_tidehunter,2).
contain(evolve_shaman,evolve,2).
contain(evolve_shaman,spirit_claws,2).
contain(evolve_shaman,maelstrom_portal,2).
contain(evolve_shaman,pantry_spider,2).

contain(zoolock,acidic_swamp_ooze,1).
contain(zoolock,flame_imp,2).
contain(zoolock,dire_wolf_alpha,2).
contain(zoolock,voidwalker,2).
contain(zoolock,knife_juggler,2).
contain(zoolock,demonfire,1).
contain(zoolock,doomguard,2).
contain(zoolock,soulfire,2).
contain(zoolock,defender_of_argus,2).
contain(zoolock,imp_gang_boss,2).
contain(zoolock,dark_peddler,2).
contain(zoolock,possessed_villager,2).
contain(zoolock,darkshire_librarian,2).
contain(zoolock,darkshire_councilman,2).
contain(zoolock,malchezaars_imp,2).
contain(zoolock,silverware_golem,2).

contain(renouncelock,mortal_coil,2).
contain(renouncelock,hellfire,2).
contain(renouncelock,corruption,2).
contain(renouncelock,drain_life,2).
contain(renouncelock,demonfire,2).
contain(renouncelock,soulfire,2).
contain(renouncelock,siphon_soul,2).
contain(renouncelock,shadow_bolt,2).
contain(renouncelock,bane_of_doom,2).
contain(renouncelock,curse_of_rafaam,2).
contain(renouncelock,renounce_darkness,2).
contain(renouncelock,yshaarj_rage_unbound,1).
contain(renouncelock,spreading_madness,2).
contain(renouncelock,forbidden_ritual,2).
contain(renouncelock,barnes,1).
contain(renouncelock,kara_kazham,2).

contain(control_warrior,sylvanas_windrunner,1).
contain(control_warrior,shield_slam,2).
contain(control_warrior,big_game_hunter,1).
contain(control_warrior,gorehowl,1).
contain(control_warrior,slam,2).
contain(control_warrior,execute,2).
contain(control_warrior,brawl,2).
contain(control_warrior,senjin_shieldmasta,2).
contain(control_warrior,acolyte_of_pain,1).
contain(control_warrior,deathwing,1).
contain(control_warrior,shield_block,1).
contain(control_warrior,cairne_bloodhoof,1).
contain(control_warrior,ragnaros_the_firelord,1).
contain(control_warrior,harrison_jones,1).
contain(control_warrior,fiery_war_axe,2).
contain(control_warrior,armorsmith,2).
contain(control_warrior,revenge,1).
contain(control_warrior,nexus-champion_saraad,1).
contain(control_warrior,justicar_trueheart,1).
contain(control_warrior,tournament_medic,1).
contain(control_warrior,bash,2).
contain(control_warrior,refreshment_vendor,1).

contain(patron_warrior,frothing_berserker,2).
contain(patron_warrior,whirlwind,2).
contain(patron_warrior,execute,1).
contain(patron_warrior,acolyte_of_pain,2).
contain(patron_warrior,abomination,2).
contain(patron_warrior,armorsmith,2).
contain(patron_warrior,deaths_bite,2).
contain(patron_warrior,unstable_ghoul,2).
contain(patron_warrior,grim_patron,2).
contain(patron_warrior,revenge,1).
contain(patron_warrior,bolster,2).
contain(patron_warrior,fierce_monkey,2).
contain(patron_warrior,tentacle_of_nzoth,2).
contain(patron_warrior,ravaging_ghoul,2).
contain(patron_warrior,bloodhoof_brave,2).
contain(patron_warrior,protect_the_king,2).


contain_with(X,Y) :-
  deck_name(X),
  card(Y),
  ((Z is 1);(Z is 2)),
  contain(X,Y,Z).

% contain_with_test(X,List) :-
%   deck_name(X),
%   nth0(I, List, CardName, R),
%   card(CardName),
%   ((Z is 1);(Z is 2)),
%   contain(X,CardName,Z).
