deck_name(face_hunter).
deck_name(malygos_druid).
deck_name(freeze_mage).
deck_name(nzoth_paladin).
deck_name(summoner_priest).
deck_name(miracle_rogue).
deck_name(midrange_shaman).
deck_name(renolock).
deck_name(dragon_warrior).
deck_name(beast_driud).
deck_name(token_driud).
deck_name(secret_hunter).
deck_name(midrange_hunter).
deck_name(tempo_mage).
deck_name(control_mage).
deck_name(dragon_paladin).
deck_name(dragon_priest).
deck_name(nzoth_rogue).
deck_name(malygos_rogue).
deck_name(aggro_shaman).
deck_name(evolve_shaman).
deck_name(zoolock).
deck_name(renouncelock).
deck_name(control_warrior).
deck_name(patron_warrior).
